Add TimeLimit to more unit tests
os-autoinst/openQA pull request #3367
Opened 2020-09-07 13:02 UTC by kalikiana

Specifying generous timeouts gives better, faster failures (as opposed to being stopped forcibly by CircleCI with no error message).

See: [poo#66664](https://progress.opensuse.org/issues/66664)

2020-09-08 06:28 UTC, okurz approved these changes
I fully agree. Adding a sensible timeout to each test module was always the idea :)

2020-09-08 07:00 UTC, okurz requested changes
But I guess we should already from a start select a timeout way below the 10m deadline timeout that circleCI uses, i.e. lower than 600s.

2020-09-08 07:48 UTC, kalikiana commented
> But I guess we should already from a start select a timeout way below the 10m deadline timeout that circleCI uses, i.e. lower than 600s.

You mean the "no output" timeout? From my previous testing we need 800s to run those tests.

2020-09-08 11:54 UTC, okurz commented
how would 800s timeout help when circleci already aborts in before if there was no output for 10m ~ 600s?

2020-09-09 05:54 UTC, okurz approved these changes

2020-09-15 12:06 UTC, merged