tests: Increase the timeout for the test 34-developer_mode-unit
os-autoinst/openQA pull request #3510
Opened 2020-11-04 14:05 UTC by ilausuch

Problem: This test is eventually failing because of timeout.
For instance: https://app.circleci.com/pipelines/github/os-autoinst/openQA/4733/workflows/65889b6b-1b18-4067-85fa-d5e325db32a6/jobs/45180

Solution: Increase the timeout to the double.

2020-11-04 14:08 UTC, kalikiana approved these changes

2020-11-04 14:48 UTC, Martchus approved these changes
I've checked out the log you've referenced. Maybe the test really just hangs at `# Waiting for finished event to become available`. But we'll see that when the test still fails after merging this PR. Note that it runs in ~5 seconds on my machine so at least from that perspective the timeout of 10 seconds seemed reasonable.

2020-11-04 14:50 UTC, Martchus requested changes
It already fails again in *this* PR so it doesn't help. The test seems stuck in `# Waiting for finished event to become available` after `ok 12 - connection to os-autoinst closed` and we need to find out why. Increasing the timeout will not gain us much.

2020-11-04 15:00 UTC, ilausuch commented
> It already fails again in _this_ PR so it doesn't help. The test seems stuck in `# Waiting for finished event to become available` after `ok 12 - connection to os-autoinst closed` and we need to find out why. Increasing the timeout will not gain us much.

Yes, I agree, we have to find the problem behind

2020-11-04 15:13 UTC, kalikiana commented
> It already fails again in _this_ PR so it doesn't help. The test seems stuck in `# Waiting for finished event to become available` after `ok 12 - connection to os-autoinst closed` and we need to find out why. Increasing the timeout will not gain us much.

Note that it's not the same.

```
[14:22:53] t/34-developer_mode-unit.t ................................ 2/? Bailout called.  Further testing stopped:  finished event not available
FAILED--Further testing stopped: finished event not available
```

versus the previous failure on master

```
[12:23:45] t/34-developer_mode-unit.t ................................ 10/? Bailout called.  Further testing stopped:  test exceeds runtime limit of '60' seconds
FAILED--Further testing stopped: test exceeds runtime limit of '60' seconds
```

2020-11-04 17:53 UTC, okurz commented
@kalikiana same-same but different :) I think it's a different symptom where the correct message isn't shown but the problem is still the same, the test module is terminated after the timeout is reached.

2020-11-05 20:01 UTC, okurz commented
I have created https://github.com/os-autoinst/openQA/pull/3518 to revert the faulty change leading to the recent problems. I also verified locally that increasing the timeout won't help.

2020-11-06 08:19 UTC, ilausuch commented
> I have created #3518 to revert the faulty change leading to the recent problems. I also verified locally that increasing the timeout won't help.

So this PR should be closed

2020-11-06 08:19 UTC, closed without merging