docker: Simplify worker Dockerfile with executable scripts
os-autoinst/openQA pull request #3547
Opened 2020-11-11 21:07 UTC by okurz

2020-11-12 09:33 UTC, Martchus approved these changes

2020-11-20 06:39 UTC, ilausuch requested changes
I had problems in the past avoiding these lines, because when the container was created the execution permissions flags was removed. I didn't remove this part. This don't provide an advantage.

2020-11-20 13:14 UTC, okurz commented
I hope the test result in https://github.com/os-autoinst/openQA/pull/3547#issue-519451465 convinces you :)

2020-11-23 15:26 UTC, ilausuch approved these changes
Thanks for the test

2020-11-24 01:41 UTC, merged