Install qemu-hw-display-virtio-gpu-pci in openqa-bootstrap
os-autoinst/openQA pull request #3643
Opened 2020-12-15 10:40 UTC by asdil12

Ticket: https://progress.opensuse.org/issues/81064

qemu-hw-display-virtio-gpu-pci is not required but only recommended.
So it needs to be explicitly installed.

2020-12-15 10:44 UTC, Martchus approved these changes
It is just 14 KiB so I guess it can not hurt to install it.

2020-12-15 10:45 UTC, ggardet commented
This is fine for Tumbleweed, but I think it would break on older distro, such as Leap 15.2.

2020-12-15 10:51 UTC, asdil12 commented
The new code should only install the pkg if it is available.

2020-12-15 11:03 UTC, ggardet approved these changes
LGTM, thanks!

2020-12-15 11:24 UTC, okurz requested changes
A shell script that is meant for generic openQA bootstrapping should not do package dependency management. Also the package is not useful nor necessary for many use cases. Maybe it's better solved with convenience sub-packages within the spec file.

Also this looks like it's really depending on what we do for os-autoinst by default so probably better solved in os-autoinst

2020-12-15 11:38 UTC, asdil12 commented
@okurz I have no idea what you mean. How should adding more subpackages (to whatever spec) resole an issue that was created by someone moving a qemu functionality into a subpackage?
And how do you think could this be resolved in os-autoinst? By calling qemu in a way that doesn't require that dependency?

I'm not sure if we are talking about the same topic. Are you maybe talking about https://bugzilla.opensuse.org/show_bug.cgi?id=1180048 ? I thing this is a separate issue that has nothing to do with that odd openQA dependency problem.

2020-12-15 14:27 UTC, okurz approved these changes
No, this has nothing to do with https://bugzilla.opensuse.org/show_bug.cgi?id=1180048 which is solved within https://progress.opensuse.org/issues/81038 and https://github.com/os-autoinst/openQA/pull/3644

> And how do you think could this be resolved in os-autoinst? By calling qemu in a way that doesn't require that dependency?

No, not call qemu differently. I thought of specifying the dependencies in https://github.com/os-autoinst/os-autoinst/blob/master/dist/rpm/os-autoinst.spec in a new sub-package similar to https://github.com/os-autoinst/os-autoinst/blob/master/dist/rpm/os-autoinst.spec#L120 for example.

As an alternative consider to change it in the tests https://github.com/os-autoinst/os-autoinst-distri-opensuse/tree/master/tests/openqa

By the way, os-autoinst does not *require* qemu because there are many backends which do not have a relation to or dependency on qemu and it is for the user to define in what environment and with what backend os-autoinst should be run. For example for a s390x z/VM openQA worker no qemu is required, neither for baremetal support.

On the other hand of course something like "openqa-bootstrap" should provide something like a good convenient default support which can include qemu so that the user can "right away" run usual tests. 
I see now that we already install multiple other packages for the same reason. Hence I can approve because you are not making it much worse :) But I wonder if we would not be better off with installing with recommendations included.

2020-12-30 10:42 UTC, kalikiana commented
@asdil12 I think this needs a rebase

2021-01-02 06:08 UTC, merged

2021-01-11 13:21 UTC, ggardet commented on script/openqa-bootstrap
> +if zypper -n search -x qemu-hw-display-virtio-gpu-pci ; then
I Think this should be negated with a `!`:
`if ! zypper -n search -x qemu-hw-display-virtio-gpu-pci ; then`