Add SUSE Linux Enterprise Micro in the external reporting
os-autoinst/openQA pull request #3678
Opened 2021-01-19 12:37 UTC by jlausuch

We have SLE Micro product which is different than OpenSUSE MicroOS
However, in bugzilla.suse.com there is no new product created yet.
I will modify it if a new product entry is created.

2021-01-19 12:45 UTC, jlausuch commented
@okurz

2021-01-19 12:53 UTC, okurz approved these changes

2021-01-19 15:02 UTC, jlausuch commented
@okurz I don't have rights to merge, I see some CI failures, but I guess recurrent and not related to this change. Could you please merge if appropriate?

2021-01-19 15:23 UTC, Martchus requested changes
The CI failures are related:

```
[error] [JTtZJqbD] Bareword "sle" not allowed while "strict subs" in use at template branding/openSUSE/external_reporting.html.ep line 18.
Context:
  13:     opensuse => 'https://bugzilla.opensuse.org/enter_bug.cgi',
  14:     caasp => 'https://bugzilla.suse.com/enter_bug.cgi',
  15:     openqa => 'https://progress.opensuse.org/projects/openqav3/issues/new',
  16:     kubic => 'https://bugzilla.opensuse.org/enter_bug.cgi',
  17:     microos => 'https://bugzilla.opensuse.org/enter_bug.cgi',
  18:     sle-micro => 'https://bugzilla.suse.com/enter_bug.cgi',
  19: );%>
```

2021-01-19 15:23 UTC, Martchus commented on templates/webapi/branding/openSUSE/external_reporting.html.ep
> +    sle-micro => 'https://bugzilla.suse.com/enter_bug.cgi',
```suggestion
    'sle-micro' => 'https://bugzilla.suse.com/enter_bug.cgi',
```

2021-01-19 15:23 UTC, Martchus commented on templates/webapi/branding/openSUSE/external_reporting.html.ep
> +    sle-micro => 'SUSE Linux Enterprise Micro',
```suggestion
    'sle-micro' => 'SUSE Linux Enterprise Micro',
```

2021-01-19 15:28 UTC, jlausuch commented on templates/webapi/branding/openSUSE/external_reporting.html.ep
> +    sle-micro => 'https://bugzilla.suse.com/enter_bug.cgi',
and what about all other entries?

2021-01-19 15:35 UTC, Martchus approved these changes

2021-01-20 01:41 UTC, kalikiana approved these changes

2021-01-20 05:09 UTC, merged

2021-01-20 10:51 UTC, okurz commented
@jlausuch commonly we don't force merge if we just *think* a CI error might be unrelated :) I am convinced that this is a recipe for failure and rather bad habit. Take every CI error serious. Sure, there can be unrelated problems but I suggest to always handle CI problems before accepting them as "unrelated". Of course, that is certainly the responsibility of the main contributors which can always be asked for help.

@Martchus @kalikiana are the coverage changes in t/lib/OpenQA/SeleniumTest.pm and t/lib/OpenQA/Test/Utils.pm known and planned accordingly in tickets?

2021-01-20 12:27 UTC, kalikiana commented
> @Martchus @kalikiana are the coverage changes in t/lib/OpenQA/SeleniumTest.pm and t/lib/OpenQA/Test/Utils.pm known and planned accordingly in tickets?

Covered by [poo#80800](https://progress.opensuse.org/issues/80274) me thinks. I'll propose something