Fix tidy
os-autoinst/openQA pull request #3733
Opened 2021-02-16 13:49 UTC by andrii-suse

2021-02-16 14:06 UTC, Martchus commented on docs/Contributing.asciidoc
> +Example commands to manually fix ci-packages.txt:
```suggestion
Example command to manually fix ci-packages.txt:
```

2021-02-16 14:06 UTC, Martchus commented on docs/Contributing.asciidoc
> +docker run --rm -v$(pwd):/opt/testing_area registry.opensuse.org/devel/openqa/ci/containers/base:latest .circleci/build_dependencies.sh
```suggestion
docker run --rm -v"$PWD:/opt/testing_area registry.opensuse.org/devel/openqa/ci/containers/base:latest" .circleci/build_dependencies.sh
```

2021-02-16 14:06 UTC, Martchus commented on .circleci/build_cache.sh
> +sudo zypper ar -f -p 90 http://download.opensuse.org/repositories/devel:/openQA:/Leap:/15.2/openSUSE_Leap_15.2 openQA
That's not just a documentation change. Why do you change the protocol here?

2021-02-16 16:21 UTC, okurz requested changes
what @Martchus said

2021-02-17 15:03 UTC, Martchus commented on docs/Contributing.asciidoc
> +docker run --rm -v$(pwd):/opt/testing_area registry.opensuse.org/devel/openqa/ci/containers/base:latest .circleci/build_dependencies.sh
When running this command I get:

```
Problem: nothing provides perl(File::Map) needed by openQA-devel-4.6.1613477586.fa28c153e-lp152.3674.1.noarch
 Solution 1: do not install openQA-devel-4.6.1613477586.fa28c153e-lp152.3674.1.noarch
 Solution 2: break openQA-devel-4.6.1613477586.fa28c153e-lp152.3674.1.noarch by ignoring some of its dependencies
```

Does someone has to do some updating before?

2021-02-17 16:41 UTC, kalikiana commented
I assume this is also obsolete now since #3726 included a commit with the fixes.

2021-02-17 16:41 UTC, closed without merging