[WIP] ensure an error if build fails
os-autoinst/openQA pull request #3831
Opened 2021-04-08 10:34 UTC by ilausuch

https://progress.opensuse.org/issues/90614

2021-04-09 12:09 UTC, Martchus commented
Can you fix the typo in the commit message?

2021-04-09 12:14 UTC, okurz requested changes
typo

2021-04-09 12:14 UTC, okurz commented on .mergify.yml
> +      - "status-success=webui-docker-compose"
please move up to come after "OBS Package Build", same as in line 16

2021-04-12 05:18 UTC, okurz approved these changes

2021-04-12 10:26 UTC, Martchus approved these changes

2021-04-13 09:34 UTC, kalikiana approved these changes
Thank you for adding that. I'd completely missed it!

2021-04-13 09:34 UTC, merged