Make potential not-implemented states of jobs obvious with die
os-autoinst/openQA pull request #3877
Opened 2021-04-30 10:30 UTC by okurz

2021-04-30 10:40 UTC, Martchus requested changes
In production this will result in a 500 error page for the user and we'd have to dig into the logs to find the exact error message. That's also not very nice. I'd rather put a warning somewhere on the web page if we consider this important enough or completely remove the code path. Or we'd simply add a category "other" where we would add the states/results to.

2021-04-30 12:57 UTC, okurz commented
Right, so if the die is handled that way by presenting 500 to the user then surely this PR in the current form is no improvement. I have a different preference though. An error in the logs is still better than in the webUI. The webUI is meant for users, the log for admins. That we don't look into logs (anymore) is our problem as admins. For that we also have https://github.com/os-autoinst/openqa-logwarn . But maybe an adjustment of your "other" proposal we can just count the unidentified as "unfinished" together. See my updated proposal.

2021-04-30 15:39 UTC, Martchus approved these changes
I guess counting these into unfinished makes sense. We handle already cancelled and done and it is unlikely that we introduce more "finished" states in the future.

2021-05-05 06:11 UTC, kalikiana commented
Can you please add a description with e.g. a ticket or discription of what you're trying to achieve?

2021-05-05 08:41 UTC, okurz commented
Is the second line "Helps with statement coverage in tests as well :)" in the commit message enough?

2021-05-05 09:40 UTC, kalikiana commented
> Is the second line "Helps with statement coverage in tests as well :)" in the commit message enough?

Not really. I'm still wondering what conversation or investigation this helps with "as well".

2021-05-05 10:22 UTC, okurz commented
@kalikiana updated the git commit message with more details and also a ticket reference and copied that into the PR description.

2021-05-05 11:16 UTC, okurz commented
created https://progress.opensuse.org/issues/92164 for the test failure which I consider unrelated. Will retrigger.

2021-05-10 10:25 UTC, kalikiana commented
11:17:17] t/01-test-utilities.t ..................................... 
    #   Failed test 'test would have failed'
    #   at t/01-test-utilities.t line 49.

    #   Failed test 'manual termination via stop_service does not trigger _fail_and_exit'
    #   at t/01-test-utilities.t line 63.
    #          got: '1'
    #     expected: '0'
    # Looks like you failed 2 tests of 5.

2021-05-10 14:23 UTC, merged