dist: Also save update-cache.sh from OBS
os-autoinst/openQA pull request #3946
Opened 2021-06-11 11:16 UTC by okurz

2021-06-11 11:35 UTC, Martchus approved these changes

2021-06-11 11:38 UTC, Martchus requested changes
The documentation should be updated as well: https://github.com/os-autoinst/openQA/blob/master/docs/Contributing.asciidoc#update-asset-cache

The script still needs to run within the osc checkout but is not located there anymore (which is currently implied).

2021-06-15 18:06 UTC, okurz commented
Updated the documentation

2021-06-16 08:15 UTC, Martchus approved these changes

2021-06-17 12:46 UTC, kalikiana approved these changes

2021-06-17 12:47 UTC, merged