BugLinks: Do not attempt label with incomplete referer URLs
os-autoinst/openQA pull request #3985
Opened 2021-06-29 10:55 UTC by asdil12

Ticket: https://progress.opensuse.org/issues/94774

All common bugtrackers use decimal bugids so check if
the referer URL is complete by making sure that it contains
a digit.

2021-06-29 10:59 UTC, perlpunk approved these changes

2021-06-29 11:16 UTC, perlpunk commented
There might be bugtrackers having a digit in their hostname, though.
Maybe check if the URI path has a length > 0 (`http://bugtracker.example/bug/123`) or if there is a query string.

2021-06-29 11:36 UTC, okurz requested changes
Please look into tests first ensuring what you want to achieve before going into an implementation. I don't think it's a good idea to introduce an additional restricting for "how does a ticket reference look like" only within the "mark_job_linked" function. We have multiple more places where we handle ticket references and we don't want them to apply different rules. But I agree that a bare link to "bugzilla.suse.com" is not helpful and we can handle that.

2021-06-29 15:16 UTC, asdil12 commented
Updated the PR.
I'm going with Tina's approach here as it is agnostic of the bugtracker used.

2021-06-29 15:20 UTC, Martchus requested changes

2021-06-29 15:20 UTC, Martchus commented on lib/OpenQA/Schema/ResultSet/Jobs.pm
> +      unless grep { $referer->host eq $_ } @{$app->config->{global}->{recognized_referers}};
Avoid repeated calls of the same function:
```suggestion
    return undef unless my $referer_host = $referer->host;
    return log_debug("Unrecognized referer '$referer_host'")
      unless grep { $referer_host eq $_ } @{$app->config->{global}->{recognized_referers}};
```

2021-06-29 15:20 UTC, Martchus commented on lib/OpenQA/Schema/ResultSet/Jobs.pm
> +    return undef if $referer->path_query =~ /^\/?$/;
```suggestion
    return undef if !$job || ($referer->path_query =~ /^\/?$/);
```

2021-06-29 16:58 UTC, okurz commented
I can think of use cases where referral URLs without anything after a slash would make sense. Would the current way not also stumble over URLs like http://bug.tracker/issue/42/ ?

2021-06-30 08:33 UTC, asdil12 commented
> I can think of use cases where referral URLs without anything after a slash would make sense. Would the current way not also stumble over URLs like http://bug.tracker/issue/42/ ?

```perl
perl> Mojo::URL->new("http://bug.tracker/issue/42/")->path_query;
/issue/42/
```

No - that should be covered, as I'm using the combined path and get parameters.

2021-06-30 11:46 UTC, okurz requested changes

2021-06-30 11:46 UTC, okurz commented on t/10-jobs.t
> +        '/tests/' . $job->id . '/modules/' . $module->id . '/steps/1' => {Referer => 'http://test.referer.info/foobar'})
To prevent the line split I suggest to pull out the string 'http://test.referer.info/foobar' into a variable which you can reuse

2021-06-30 12:57 UTC, okurz approved these changes

2021-06-30 14:31 UTC, Martchus approved these changes

2021-06-30 14:32 UTC, merged