Fix carry-over only due to one matching bugref in step title
os-autoinst/openQA pull request #3988
Opened 2021-06-29 15:09 UTC by Martchus

* Prevent carry-over despite a mismatch of failing test modules like in
  https://progress.opensuse.org/issues/94880
* Still allow carry-over when the same bug is found via different modules
  (ef5f07c561cb4bb6139d17b98b616af6b81a8fff) but only if the other failing
  test modules match as well

---

Still a draft because it lacks tests.

2021-06-29 16:44 UTC, okurz commented
I like the code style change :)

2021-06-30 11:22 UTC, Vogtinator approved these changes
The algorithm seems sound to me.

The only weakness I could identify is that when a failed module gains a bugref in test code, that blocks carryover. Shouldn't really be an issue in practice, and the previous code had that as well.

2021-06-30 11:25 UTC, Martchus commented
> The only weakness I could identify is that when a failed module gains a bugref in test code, that blocks carryover. Shouldn't really be an issue in practice, and the previous code had that as well.

I thought about it as well but thought it wasn't worth it as it would complicate the code a bit. We can still implement it later if needed.

2021-06-30 11:31 UTC, okurz commented on t/17-labels_carry_over.t
> +      'no carry-over when 3rd module failes, despite a matching bugref between other modules';
s/failes/fails/

2021-06-30 11:58 UTC, okurz commented on t/17-labels_carry_over.t
> +    $mock->redefine(results => undef);
`$mock->noop('results')`?

2021-06-30 12:01 UTC, okurz requested changes
Sorry, I don't understand. What has the "carry-over" have to do with "matching bugref in step title"? I thought carry-over is only looking at failed modules, not steps?

2021-06-30 12:04 UTC, Martchus commented
> I thought carry-over is only looking at failed modules, not steps?

That is wrong. With https://github.com/os-autoinst/openQA/commit/ef5f07c561cb4bb6139d17b98b616af6b81a8fff (referenced in the commit message) it has been changed to also take bugrefs within step titles into account.

2021-06-30 12:29 UTC, okurz approved these changes

2021-06-30 15:07 UTC, kalikiana approved these changes

2021-06-30 15:08 UTC, merged