Take test modules without result into account for carry-over
os-autoinst/openQA pull request #3991
Opened 2021-06-30 10:43 UTC by Martchus

This should be a small fix for https://progress.opensuse.org/issues/70915 (based on #3988).

2021-06-30 11:33 UTC, okurz commented on t/17-labels_carry_over.t
> +      'no carry-over when 3rd module failes, despite a matching bugref between other modules';
s/failes/fails/

2021-06-30 12:47 UTC, okurz commented on lib/OpenQA/Schema/Result/Jobs.pm
> +        next unless $module_result eq FAILED || $module_result eq SOFTFAILED || $module_result eq NONE;
```perl
sub _relevant_module_result_for_carry_over_evaluation {
    module_result ne FAILED && $module_result ne SOFTFAILED && $module_result ne NONE;
}

…
    next if _relevant_module_result_for_carry_over_evaluation($module_result);
```

2021-06-30 12:47 UTC, okurz requested changes
please rebase on the other PR's branch and one function extraction to have a better name for the important logic

2021-06-30 15:20 UTC, okurz approved these changes

2021-07-01 02:10 UTC, Amrysliu approved these changes

2021-07-01 02:10 UTC, merged