Retry the assets package generation if a CDN fails
os-autoinst/openQA pull request #4094
Opened 2021-07-30 10:51 UTC by ilausuch

We observed this kind of errors in the openqa test at install_from_git

[warn] [AssetPack] Unable to download https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css: Connect timeout

This PR introduces a retry on the tools/generate-packet-assets in
case the asset download fails

https://progress.opensuse.org/issues/95995

2021-07-30 11:09 UTC, Martchus requested changes

2021-07-30 11:09 UTC, Martchus commented on tools/generate-packed-assets
> +    env MOJO_MODE=$1 perl $BUILD_CACHE_OPTS -e "$BUILD_CACHE" > /dev/null
This should nevertheless be quoted:
```suggestion
    env MOJO_MODE="$1" perl $BUILD_CACHE_OPTS -e "$BUILD_CACHE" > /dev/null
```
The same counts for the other function.

2021-07-30 11:09 UTC, Martchus commented on tools/generate-packed-assets
> +generate () {
```suggestion
generate() {
```

2021-07-30 11:09 UTC, Martchus commented on tools/generate-packed-assets
> +generate_retry (){
```suggestion
generate_retry() {
```

2021-07-30 11:09 UTC, Martchus commented on tools/generate-packed-assets
> +# Required a retry in case of cdn failure
```suggestion
# Possibly requires a retry in case of CDN failures
```

2021-07-30 11:23 UTC, ilausuch commented
Thanks @Martchus fixed

2021-07-30 11:32 UTC, Martchus requested changes

2021-07-30 11:32 UTC, Martchus commented on tools/generate-packed-assets
> +    generate $1 || (sleep 1; generate $1 || exit 1) || (sleep 1; generate $1 || exit 1)
In my last comment I said the other function needs quotes as well. Additionally, you don't need the explicit exit:
```suggestion
    generate "$1" || (sleep 1; generate "$1") || (sleep 1; generate "$1")
```

Spawning sub-shells also seems needless, e.g. one could easily write it as:
```suggestion
    [[ $2 ]] && sleep "$2"
    generate "$1" || generate "$1" "1" || generate "$1" "1"
```

2021-07-30 12:03 UTC, ilausuch commented
I test this forcing an error in the assets list
```
tools/generate-packed-assets
[2021-07-30 12:03:12.34786] [49188] [warn] [AssetPack] Unable to download https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css2: Not Found
Could not find input asset "https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css2". at /usr/lib/perl5/vendor_perl/5.32.1/Mojolicious/Plugin/AssetPack.pm line 172.
[2021-07-30 12:03:13.62006] [49197] [warn] [AssetPack] Unable to download https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css2: Not Found
Could not find input asset "https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css2". at /usr/lib/perl5/vendor_perl/5.32.1/Mojolicious/Plugin/AssetPack.pm line 172.
[2021-07-30 12:03:14.89508] [49212] [warn] [AssetPack] Unable to download https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css2: Not Found
Could not find input asset "https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css2". at /usr/lib/perl5/vendor_perl/5.32.1/Mojolicious/Plugin/AssetPack.pm line 172.

2021-07-30 12:05 UTC, Martchus approved these changes

2021-07-30 12:24 UTC, okurz commented on tools/generate-packed-assets
> +    generate "$1" || generate "$1" "1" || generate "$1" "1"
why not the for-loop I suggested?

```suggestion
    for i in {1..3}; do
        # shellcheck disable=SC2086
        env MOJO_MODE="$1" perl $BUILD_CACHE_OPTS -e "$BUILD_CACHE" > /dev/null && return 0
        sleep 1
    done
```

2021-07-30 12:40 UTC, Martchus commented on tools/generate-packed-assets
> +    generate "$1" || generate "$1" "1" || generate "$1" "1"
That would apparently be too easy :-)

2021-07-30 13:22 UTC, okurz requested changes
see above

2021-08-02 10:40 UTC, ilausuch commented on tools/generate-packed-assets
> +    generate "$1" || generate "$1" "1" || generate "$1" "1"
done

2021-08-02 13:06 UTC, okurz approved these changes

2021-08-03 07:54 UTC, okurz commented
@ilausuch please call shellcheck manually. For something as simple as static checks you should not rely on CI only: https://app.circleci.com/pipelines/github/os-autoinst/openQA/7279/workflows/a5957bb9-56a1-4e79-9607-8338f4628ad3/jobs/68626

2021-08-03 09:07 UTC, merged