Fetchneedles improvements
os-autoinst/openQA pull request #4203
Opened 2021-09-14 18:27 UTC by phil-hands

This is mostly about making it easy to subsequently tune options used by downstream distros, but I think the changes should be of some benefit for OpenSUSE too.

I've not enabled the git-lfs change here (since you don't use it) but can assure you that it's been in use for openqa.debian.net (and workers) for months, and it works well.

2021-09-16 10:31 UTC, Martchus approved these changes

2021-09-19 20:52 UTC, okurz requested changes

2021-09-19 20:52 UTC, okurz commented on script/fetchneedles
> +: "${dist_name:=${dist:-"OpenSUSE"}}" # the display name, for the help message
It's actually "openSUSE" with a lowercase leading character.
It's only for the help text but I am sure you understand that we should be consistent about the project's names :)

2021-11-23 09:40 UTC, okurz commented on script/fetchneedles
> +: "${dist_name:=${dist:-"OpenSUSE"}}" # the display name, for the help message
Fixed that with an updated commit

2021-11-23 09:40 UTC, okurz approved these changes

2021-11-23 11:00 UTC, Martchus commented
Shellcheck has some remarks, see the output of the "ci/circleci: checkstyle` check.

2021-11-23 12:01 UTC, phil-hands commented
> Shellcheck has some remarks, see the output of the "ci/circleci: checkstyle` check.

Fair enough -- here's a fix for that:  https://github.com/phil-hands/openQA/commit/3bd81e12067a8ffd7135a98f9aad57b8857283ac

Do you want that as a new pull request, or is that enough as it is?

BTW I've only tested that it produces the expected output, which it did, but not yet tried it out beyond that ... which ought to be fine since this is in a conditional that only runs with -h/--help options.

Cheers, Phil.

2021-11-23 12:54 UTC, merged

2021-11-23 14:22 UTC, okurz commented
@phil-hands thanks for the update. With the help of mergify you could see that we are good with the current pull request ;)