Mark non-existing asset as such in the downloads tab
os-autoinst/openQA pull request #4212
Opened 2021-09-17 14:45 UTC by Martchus

* It was brought up in the chat that the UI could be more clear here
* Maybe helps with https://progress.opensuse.org/issues/98388 as well

2021-09-17 16:37 UTC, kalikiana approved these changes

2021-09-19 19:48 UTC, okurz requested changes
failure in t/05-scheduler-full.t: https://app.circleci.com/pipelines/github/os-autoinst/openQA/7726/workflows/d9c5ff5f-2d11-4862-9326-d919e334f4b6/jobs/72940/steps . Does not look related but should not go unhandled.

2021-09-20 09:39 UTC, Martchus commented
Looks like the problem persists after restarting. It still looks unrelated and locally the test passes. So I'm creating a ticket.

2021-09-20 16:24 UTC, pevik approved these changes

2021-09-21 07:38 UTC, merged