Add OPENQA_HOSTNAME to the job settings
os-autoinst/openQA pull request #4216
Opened 2021-09-20 16:22 UTC by foursixnine

When a worker is shared for certain jobs, specially when it comes to svirt jobs, can become a bit difficult to figure out in which webUI a
job has been executed or triggered from, leaving room for potential collisions (see poo#97532 for instance)

2021-09-20 16:40 UTC, okurz requested changes
I don't understand how you would find jobs if not over the webUI unless this is about workers rich don't delete it's pool dir. Could you explain again for dummies like me?

2021-09-20 16:42 UTC, foursixnine commented
@okurz see https://github.com/os-autoinst/os-autoinst/pull/1777 :)

2021-09-20 20:51 UTC, okurz approved these changes

2021-09-21 07:27 UTC, merged

2021-09-22 05:40 UTC, okurz commented
@foursixnine please leave merging to mergify by default

2021-09-22 07:50 UTC, foursixnine commented
> @foursixnine please leave merging to mergify by default

Right! Force of habit :)