Change $job->cancel to have possibility set reason
os-autoinst/openQA pull request #4341
Opened 2021-10-27 07:59 UTC by mimi1vx

2021-11-03 19:14 UTC, mimi1vx commented on lib/OpenQA/Schema/ResultSet/Jobs.pm
> +          += _cancel_or_deprioritize($j, OpenQA::Jobs::Constants::OBSOLETED, $ddeprioritize, $deprio_limit);
in whole file and also in others is usage of constants same as this, so I don't think s good idea import one constant

2021-11-04 09:16 UTC, Martchus requested changes

2021-11-04 09:16 UTC, Martchus commented on lib/OpenQA/Schema/ResultSet/Jobs.pm
> +    return $job->cancel(OpenQA::Jobs::Constants::OBSOLETED) // 0;
This will now always set jobs to `OBSOLETED`, before it possibly set them to `USER_CANCELLED`. So this change doesn't look correct.

2021-11-04 10:32 UTC, Martchus approved these changes

2021-11-08 13:02 UTC, kalikiana reviewed
Do you think we could have a test for the "obsolte" case? To be fair it doesn't seem like this was covered before. But maybe a good opportunity to add it now?

2021-11-09 10:25 UTC, okurz commented
+1

2021-11-10 16:53 UTC, mimi1vx commented
@kalikiana this https://github.com/os-autoinst/openQA/blob/a636a870555f3978e8bcf548be4c7bb0aa161660/t/04-scheduler.t#L406-L416 isn't valid test for obsolete case ?

2021-11-10 18:02 UTC, Martchus commented
I'm also not sure what he means. The diff coverage is also 100 %.

2021-11-11 11:36 UTC, kalikiana commented
> https://github.com/os-autoinst/openQA/blob/a636a870555f3978e8bcf548be4c7bb0aa161660/t/04-scheduler.t#L406-L416
> 
> isn't valid test for obsolete case ?

I meant that the test never exercises `cancel(OBSOLETE)` (and never `cancel(1)` w/o your changes).

2021-11-11 11:37 UTC, kalikiana approved these changes
No need to block on my point, since it was about extending tests.

2021-11-11 11:37 UTC, merged