apparmor: allow local additions to the worker profile
os-autoinst/openQA pull request #4371
Opened 2021-11-24 22:59 UTC by marmarek

This is useful for example with generalhw backend, which uses
site-specific auxiliary scripts that may need extra profile entries
(or even subprofiles).

This is kind of related to https://github.com/os-autoinst/os-autoinst/pull/1741, but is useful independently too.

2021-11-25 06:32 UTC, okurz reviewed
Please make the commit msg start with a capital letter after the component make, i.e. "Allow"

2021-11-25 09:21 UTC, ggardet commented
You must update the `Makefile` to actually install the new file. https://github.com/os-autoinst/openQA/blob/master/Makefile#L108

2021-11-25 14:39 UTC, Martchus requested changes
See comment by @ggardet

2021-11-25 16:59 UTC, ggardet commented
LGTM now :)

2021-11-25 17:01 UTC, Martchus approved these changes

2021-11-25 21:09 UTC, okurz commented
your base branch seems to be outdated. Please rebase on latest origin master and push again

2021-11-26 07:20 UTC, ggardet approved these changes

2021-11-26 07:55 UTC, okurz approved these changes

2021-11-26 07:56 UTC, merged