Use signatures in OpenQA::CLI::api and OpenQA::CLI::archive
os-autoinst/openQA pull request #4466
Opened 2022-01-20 17:50 UTC by FruitFly638

OpenQA/CLI/api.pm and OpenQA/CLI/archive.pm now use signatures.

https://progress.opensuse.org/issues/105127

2022-01-20 18:01 UTC, perlpunk requested changes

2022-01-20 18:01 UTC, perlpunk commented on lib/OpenQA/CLI/api.pm
> +use Mojo::Base 'OpenQA::Command' -signatures;
comma missing:
```suggestion
use Mojo::Base 'OpenQA::Command', -signatures;
```
Same below :)

2022-01-21 09:36 UTC, Martchus approved these changes

2022-01-21 11:05 UTC, okurz approved these changes

2022-01-21 11:16 UTC, perlpunk approved these changes

2022-01-21 11:16 UTC, merged