Show dependency graph also for cloned/restarted jobs
os-autoinst/openQA pull request #4507
Opened 2022-02-15 16:12 UTC by Martchus

* Do not blindly follow the clone chain to the latest job anymore
    * Display always the current job, even if it is not the latest clone
    * Avoid following the clone chain to the latest job for children if
      the child's clone is not a dependency of the parent job anymore
    * Avoid following the clone chain to the latest job for parents
* Do not display (directly) chained children of jobs when the clone depth
  does not match the one from the current job to avoid dragging too many
  jobs into the tree
* See https://progress.opensuse.org/issues/69976

2022-02-15 18:13 UTC, okurz requested changes

2022-02-15 18:13 UTC, okurz commented on lib/OpenQA/WebAPI/Controller/Test.pm
> +          = _add_job($visited, $nodes, $edges, $cluster, $cluster_by_job, $parent_job, $as_child_of, $preferred_depth)
if that wraps over multiple lines you know you have too many parameters :) Can you refactor that?

2022-02-15 18:13 UTC, okurz commented on lib/OpenQA/WebAPI/Controller/Test.pm
> +        _add_job($visited, $nodes, $edges, $cluster, $cluster_by_job, $child->child, $job_id, $preferred_depth);
same effect here as in the comment above

2022-02-15 18:13 UTC, okurz commented on lib/OpenQA/WebAPI/Controller/Test.pm
to reduce risk of deployment I suggest to split out introducing signatures into a separate commit and even separate PR that we can merge first

2022-02-16 13:46 UTC, Martchus commented
Just a few examples how it looks like. All graphs (except the last example) are real examples from our production instance.

A fully restarted dependency tree looks definitively as it should.
Original tree: ![grafik](https://user-images.githubusercontent.com/10248953/154271605-939eb00c-5499-4ac6-a95c-769cbeb1a449.png)
Restarted tree: ![grafik](https://user-images.githubusercontent.com/10248953/154271735-ee5c4c0e-413d-4d33-bc62-a3f231823dba.png)

---

Partially restarted trees also look most of the time.
Original tree: ![grafik](https://user-images.githubusercontent.com/10248953/154272351-c992250b-cf0a-48fe-bcdf-7f0938afbb43.png)
Where only the following jobs have been restarted: ![screenshot_20220216_141734](https://user-images.githubusercontent.com/10248953/154272560-e8859061-2c2c-47d6-9b4f-546b3110e7d5.png)

---

However, partially restarted trees can also look like this: ![screenshot_20220216_142013](https://user-images.githubusercontent.com/10248953/154273116-82e428ad-9c34-49d5-8a00-8e56c6067ad2.png)

In this case restarted children of another "root" job are dragged into the graph. So far I haven't found a good solution to avoid this (without impairing other cases). However, I don't consider it *that* bad. None of the parallel clusters is only shown half and it wouldn't drag any further chained children of the wrong "restart depth" into the graph.

The graph of the latest jobs is also not affected at all (so there's no regression): ![screenshot_20220216_142652](https://user-images.githubusercontent.com/10248953/154274147-42235d5d-7841-41fd-bfde-4cffefe5339c.png)

---

By the way, a partial restart plus another partial restart as described in https://github.com/os-autoinst/openQA/pull/4498#issuecomment-1031638134 looks like this:

The initial cluster is rendered exactly like one would expect it: ![screenshot_20220216_143228](https://user-images.githubusercontent.com/10248953/154275172-a2e2a20c-cd8d-4653-a5e6-1a6906b9c0d4.png)

This is the graph for the first clone of root1 (after root1 has been restarted without https://github.com/os-autoinst/openQA/pull/4498 and root2 has been restarted separately in addition and then root1 has been restarted again *with* https://github.com/os-autoinst/openQA/pull/4498): ![screenshot_20220216_143415](https://user-images.githubusercontent.com/10248953/154275526-f327b566-e0b0-4a7d-aecd-2484c502daa6.png)

It looks a bit confusing but also shows the problem I was getting at in the other PR quite nicely (that child1 has been restarted twice). So I guess having it rendered this way isn't the worst.

The graph for the latest jobs looks still simple (so again, no regression): ![screenshot_20220216_144127](https://user-images.githubusercontent.com/10248953/154276693-79ba0386-8a67-4fd0-887e-9349e8d56f86.png)
 
---

Maybe I can still tweak it further to simplify graphs of restarted jobs. However, considering those graphs weren't displayed before at all and graphs for the latest jobs are still as before I already consider this an improvement.

Of course I still need to adapt tests but I wanted to wait for feedback first.

2022-02-16 14:35 UTC, okurz commented
The example about "A fully restarted dependency" shows that in one case the "ppc64le-hmc-4disk" is coming first, and the other time at end. Can this be influenced by ordering before the data is rendered or is it really something non-predictable by the graphics rendering?

The part about "In this case restarted children of another "root" job are dragged into the graph" is a bit worrying and I don't really understand it but I would accept it for now. Rest looks fine.

2022-02-16 16:07 UTC, Martchus commented
About the first question: This is indeed inconsistent but unrelated to this change. The order in which nodes are added to the tree depends on the current job and I selected a different job in these screenshots. I suppose we could simply sort the nodes in the end, possibly even in JavaScript.

One thing I've forgotten to mention: The code should ensure that no nodes are added to the tree which are not somehow connected to other nodes. So all jobs being dragged into the graph should at least indirectly depend on the current job. (That's what the `$clone->is_child_of($as_child_of)` check is supposed to ensure.)

2022-02-18 11:37 UTC, kalikiana approved these changes

2022-02-18 11:37 UTC, kalikiana commented on t/ui/16-tests_dependencies.t
> +            '.cluster', 0, 'no cluster present (as only the latest job has dependency to cluster)'
```suggestion
            '.cluster', 0, 'no cluster present (as only the latest job depends on the cluster)'
```

2022-02-21 09:23 UTC, okurz approved these changes

2022-02-21 09:23 UTC, merged