bootstrap-container: Call update-ca-certificates
os-autoinst/openQA pull request #4525
Opened 2022-02-23 13:01 UTC by asdil12

Ticket: https://progress.opensuse.org/issues/107242

2022-02-23 13:07 UTC, asdil12 commented
Verified locally.

2022-02-23 13:53 UTC, okurz requested changes
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages. You already referenced a ticket, that is good but please also explained in a self-contained manner in the git commit message itself. Also please answer the "Why", not the "What" in the git commit message subject line. Think from the perspective of a changelog reader.

2022-02-23 17:45 UTC, Martchus commented
I suppose @okurz was after a commit message *subject* like "Fix outgoing TLS connections in bootstrap-container".

2022-02-25 10:06 UTC, perlpunk approved these changes

2022-02-25 10:09 UTC, okurz approved these changes

2022-02-25 10:09 UTC, merged