Expose bandwidth data for worker cache via InfluxDB
os-autoinst/openQA pull request #4526
Opened 2022-02-23 13:26 UTC by kraih

Progress: https://progress.opensuse.org/issues/106901

2022-02-23 13:51 UTC, okurz requested changes

2022-02-23 13:51 UTC, okurz commented on t/25-cache.t
> +is $cache->sqlite->migrations->active, 5, 'version 4 is the active version';
Now the description strings are wrong. That's the reason why the description string should not even contain the version number. Better:

```suggestion
is $cache->sqlite->migrations->latest, 5, 'Current version is the latest version';
is $cache->sqlite->migrations->active, 5, 'Current version is the active version';
```

2022-02-23 17:41 UTC, Martchus commented on lib/OpenQA/CacheService/Model/Cache.pm
> +    $metrics{$_->{name}} = $_->{value} for @$metrics;
I suppose this could use `map`.

2022-02-23 17:41 UTC, Martchus commented on t/25-cache-service.t
> +      = $app->cache->sqlite->db->query("SELECT value FROM metrics WHERE name = 'download_rate' LIMIT 1")->hash->{value};
If this would call `sub metrics` you'd directly gain coverage for it.

2022-02-24 15:08 UTC, Martchus approved these changes

2022-02-25 05:47 UTC, okurz approved these changes

2022-02-25 14:47 UTC, merged