Fix wrongly skipping directly chained jobs
os-autoinst/openQA pull request #4571
Opened 2022-03-21 17:17 UTC by Martchus

* Consider the result of the relevant directly chained parent job when
  deciding whether to skip the next job (instead of just considering the
  result of the last job that has been executed)
    * Rework queuing logic accordingly
    * In particular, keep track of the currently relevant parent when
      grabbing the next job from the queue
* See https://progress.opensuse.org/issues/108476

---

~~Still a draft because there's another problem to solve: The worker
doesn't really know whether a test has failed or not at this point (except
when the backend process exists with a non-zero exit code or some
other worker-related error happened). Hence the the logic for skipping
directly chained jobs is still flawed.~~

This is solved now by simply taking the web UI's response into account
when setting a job to done.

See the particular commit messages for detail.

2022-03-21 17:19 UTC, Martchus commented on t/24-worker-overall.t
> +            [12, [], [0]],
Each row now contains the relevant parents for the current iteration step. Otherwise everything is the same.

2022-03-22 13:56 UTC, okurz requested changes
The git commit message "api: Return result/reason correctly string when setting job done" is likely wrong. Better rephrase, the word "string" looks like it doesn't belong there

2022-03-22 17:31 UTC, okurz approved these changes

2022-03-23 10:15 UTC, kraih commented on t/24-worker-jobs.t
> +        my %a;
Better not use `a` and `b` as identifiers, they are quite magical.

2022-03-23 13:45 UTC, kraih approved these changes

2022-03-23 13:46 UTC, merged