fetchneedles to also force configuration
os-autoinst/openQA pull request #4594
Opened 2022-04-07 16:05 UTC by mpagot

the script take care to call itself with sudo -u geekotest forwarding one by one all the configurations variables.

**force** parameter forwarding  is missing

2022-04-08 06:54 UTC, okurz requested changes
Thank you for the contribution and welcome to this project :fireworks: 

The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages. Simple thangs that should be done: Phrase the git commit message subject line in imperative mood and starting with a capital letter.

What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has *only* the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.

I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [git-pr-last](http://github.com/okurz/scripts/tree/master/git-pr-last) to create a PR with proper description for these simple one-commit PRs:
```bash
$ cat $(which git-pr-last )
#!/bin/sh -e
target="${target:-"$USER"}"
git push $target && git show --no-patch --format=%B | hub pull-request -F -
```

See https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md#coding-style for more details

2022-04-08 08:43 UTC, Martchus reviewed
The change itself looks good but please improve the commit message as @okurz suggests.

2022-05-03 08:08 UTC, kalikiana commented
> The change itself looks good but please improve the commit message as @okurz suggests.

@mpagot Did you see this ask?

2022-05-03 10:55 UTC, kalikiana approved these changes

2022-05-03 11:39 UTC, okurz commented
I still don't see any details in the git commit message, did I miss something?

2022-05-03 11:55 UTC, mpagot commented
> 

commit message has been changed to one line sentence like

```
Forward the force parameter in fetchneedles script
```

2022-05-03 13:38 UTC, Martchus approved these changes

2022-05-03 13:40 UTC, okurz approved these changes

2022-05-11 16:37 UTC, merged