Allow exporting openqa-clone-job's API call for posting jobs
os-autoinst/openQA pull request #4634
Opened 2022-05-02 14:34 UTC by Martchus

See https://progress.opensuse.org/issues/110515

2022-05-02 16:45 UTC, perlpunk approved these changes

2022-05-02 16:47 UTC, okurz commented
@mergifyio rebase

2022-05-02 16:48 UTC, okurz approved these changes

2022-05-02 17:43 UTC, okurz requested changes

2022-05-02 17:43 UTC, okurz commented on t/35-script_clone_job.t
> +      'downloadinng logged (2)';
```suggestion
      'downloading logged (2)';
```

2022-05-03 10:39 UTC, okurz approved these changes

2022-05-03 10:40 UTC, okurz commented
@Mergifyio rebase

2022-05-03 11:08 UTC, merged