Introduce job setting _TRIGGER_JOB_DONE_HOOK to disable/enable hook
os-autoinst/openQA pull request #4667
Opened 2022-05-23 13:22 UTC by Martchus

This setting allows to disable/enable the hook script per job (or test
suite or wherever the setting is specified). It also comes with a generic
`job_done_hook` configuration setting which will be used in case
`_TRIGGER_JOB_DONE_HOOK=1` is specified and no result-specific job done
hook is configured anyways.

See
* https://progress.opensuse.org/issues/110518
* https://progress.opensuse.org/issues/110530

2022-05-23 20:13 UTC, okurz requested changes
just a minor remark regarding the format of comments, rest looks fine.

2022-05-23 20:13 UTC, okurz commented on etc/openqa/openqa.ini
> +# corresponding to the `$result`, for example:
please wrap lines at 80 characters

2022-05-24 11:45 UTC, okurz approved these changes

2022-05-25 09:09 UTC, kraih approved these changes

2022-05-25 09:09 UTC, merged