systemd: Depend on time being in sync if possible
os-autoinst/openQA pull request #4692
Opened 2022-06-07 12:30 UTC by kalikiana

If the system has a unit implementing time-sync the worker service will
not come up until it can rely on the time. This prevents authentication
errors due to a timestamp mismatch.

See: https://progress.opensuse.org/issues/105855

2022-06-07 12:43 UTC, okurz requested changes

2022-06-07 12:43 UTC, okurz commented on systemd/openqa-worker.target
> +After=time-sync.target
Hm, not sure if we should put this into `openqa-worker.target` or rather `openqa-worker@.service`?

2022-06-07 13:58 UTC, okurz approved these changes

2022-06-08 08:49 UTC, okurz commented
> can we be sure that the time is set when `time-sync.target` is reached?

I don't fully trust it but it's my understanding that the actual *target* means that time is synced, yes. If this does not work then there might be a problem in the time sync problem.

2022-06-08 08:53 UTC, kalikiana commented
> This looks like a good start - I wonder, if the ntp sync is done fast enough, though.
> 
> ```
> # /etc/chrony.d/pool.conf
> pool 2.suse.pool.ntp.org iburst
> ```
> 
> The `iburst` is in our default chrony configuration to ensure a quick ntp sync, but can we be sure that the time is set when `time-sync.target` is reached?

It's up to the systemd service to include time-set.target in Before= and Wants=. We rely on that by contract. See systemd.special(7)

2022-06-09 11:28 UTC, Martchus approved these changes

2022-06-09 11:29 UTC, merged