Only apply the domain passlist-check for ASSETS as documented
os-autoinst/openQA pull request #4743
Opened 2022-07-14 12:00 UTC by okurz

This fixes an unexpected error when passing seemingly arbitrary test
variables into openQA that end with _URL. While we treat _URL variables
as special to render clickable links we should not deny scheduling
products when URLs correspond to domains not on the passlist which was
only ever intended for asset downloading.

2022-07-14 12:24 UTC, Martchus requested changes

2022-07-14 12:49 UTC, okurz commented on lib/OpenQA/Utils.pm
> +        next unless asset_type_from_setting(get_url_short($param));
hm, ok. How can we discard the second return value of get_url_short?

2022-07-14 12:53 UTC, perlpunk commented on lib/OpenQA/Utils.pm
> +        next unless asset_type_from_setting(get_url_short($param));
`(get_url_short $param)[0]`

2022-07-14 14:25 UTC, Martchus approved these changes

2022-07-21 13:35 UTC, okurz commented
Sorry, this got a bit messy. Let's separate PRs. I created a new specific PR https://github.com/os-autoinst/openQA/pull/4761 now that should be much easier to test and review

2022-07-21 13:35 UTC, closed without merging