Reduce two verbose log messages to trace level
os-autoinst/openQA pull request #4808
Opened 2022-09-20 10:35 UTC by okurz

On big openQA instances with debug log level enabled I can see multiple
log messages every second which is much more verbose than other type of
messages during normal operation.

2022-09-20 10:36 UTC, Martchus approved these changes

2022-09-20 12:20 UTC, Martchus commented on lib/OpenQA/WebAPI/Controller/API/V1.pm
> +    $self->app->log->trace("Found associated job $job->id);
```
Can't find string terminator '"' anywhere before EOF at /home/squamata/project/lib/OpenQA/WebAPI/Controller/API/V1.pm line 15.
```

2022-10-01 20:35 UTC, Martchus requested changes

2022-10-01 20:35 UTC, Martchus commented on lib/OpenQA/WebAPI/Controller/API/V1.pm
> +    $self->app->log->trace("Found associated job $job->id");
You cannot call a function within `""`.

2022-10-04 11:25 UTC, Martchus approved these changes

2022-10-05 13:59 UTC, perlpunk approved these changes

2022-10-05 14:03 UTC, merged