[WIP] Work around openQA-single-instance pulling openQA on Leap 15.4
os-autoinst/openQA pull request #4901
Opened 2022-11-15 17:54 UTC by a-kpappas

Using the openQA-bootstrap script on Leap 15.4, without ssh keys in use, causes it to fail, because it pulls an older version of fetchneedles and openQA where poo#104794 has not been fixed.

However by explicitly adding openQA to the list of the packages to be installed, the problems seems to be fixed.

Related ticket: https://progress.opensuse.org/issues/115784

2022-11-15 21:37 UTC, perlpunk approved these changes

2022-11-16 08:20 UTC, okurz requested changes
Hm, so do I understand this correctly that the problem happens when openQA was installed already before starting openqa-bootstrap but from different repositories before openqa-bootstrap adds devel:openQA, right?

I guess if we add extra repositories we should better make sure we call `zypper dup` to update any already installed packages which come from devel:openQA. That can be more than just openQA.

@a-kpappas could you check if instead of explicitly selecting the "openQA" package for install – which effectively upgrades it – call `zypper dup --allow-vendor-change` after line 24 and check if that also helps in your cases.

2022-11-16 09:24 UTC, a-kpappas commented
> Hm, so do I understand this correctly that the problem happens when openQA was installed already before starting openqa-bootstrap but from different repositories before openqa-bootstrap adds devel:openQA, right?
> 

openQA is not installed, and the problematic script `fetchneedles` does not exist on the system either. These are installed by openQA-bootstrap. 

```
test-openqa:~ # zypper search -i openQA
...
S  | Name             | Summary                                              | Type
---+------------------+------------------------------------------------------+--------
i+ | openQA-bootstrap | Automated openQA setup                               | package
i  | openQA-client    | Client tools for remote openQA management            | package
i  | openQA-common    | The openQA common tools for web-frontend and workers | package
i+ | openQA-worker    | The openQA worker                                    | package
test-openqa:~ # zypper info openQA-common
```
> I guess if we add extra repositories we should better make sure we call `zypper dup` to update any already installed packages which come from devel:openQA. That can be more than just openQA.
> 
> @a-kpappas could you check if instead of explicitly selecting the "openQA" package for install – which effectively upgrades it – call `zypper dup --allow-vendor-change` after line 24 and check if that also helps in your cases.

`zypper -n dup` does work but it is a much more invasive operation, and should not be done by a random script on a Leap system. I think that just adding the openQA to the initial `zypper in`,  makes more sense, since it is **already** going to be installed

2022-11-16 10:54 UTC, okurz commented
> `zypper -n dup` does work but it is a much more invasive operation, and should not be done by a random script on a Leap system. I think that just adding the openQA to the initial `zypper in`, makes more sense, since it is **already** going to be installed

Ok, then try

```
zypper -n dup --allow-vendor-change devel:openQA:Leap:${VERSION}
zypper -n dup --allow-vendor-change devel:openQA
```

2022-11-16 12:35 UTC, a-kpappas commented
> Ok, then try
> 
> ```
> zypper -n dup --allow-vendor-change devel:openQA:Leap:${VERSION}
> zypper -n dup --allow-vendor-change devel:openQA
> ```

Those are not valid zypper commands.

2022-11-16 12:36 UTC, a-kpappas commented
What are your objections to my approach though?

2022-11-16 12:46 UTC, Martchus commented
@okurz If you wanted to use the `--repo` flag in those zypper commands then I'd say it is likely not a good idea. We've seen problems caused by this when using it in the continuous update service.

Maybe openQA-single-instance should simply require a specific openQA version (like openQA requires a specific openQA-common version). So far openQA-single-instance only indirectly depends on openQA which should likely be fixed as well.

2022-11-16 12:54 UTC, okurz commented
> Maybe openQA-single-instance should simply require a specific openQA version (like openQA requires a specific openQA-common version). So far openQA-single-instance only indirectly depends on openQA which should likely be fixed as well.

Sounds good. I don't know what you mean exactly but likely best to show in actual code changes

2022-11-17 10:07 UTC, a-kpappas commented
@okurz Should I close this then? I don´t mind using my fork in my scripts, until the `openQA-single-instance` package is updated.

2022-11-17 10:21 UTC, Martchus commented
Just change this PR to update the package instead. The spec file is in the repo.

2022-11-24 14:41 UTC, a-kpappas commented
Updating openQA-single-instance does not work.

2022-11-24 14:43 UTC, okurz commented
> Updating openQA-single-instance does not work.

what do you mean in particular?

2022-11-24 14:52 UTC, a-kpappas commented
> Just change this PR to update the package instead. The spec file is in the repo.

I assume this comment asks me to `zypper -n install -f openQA-single-instance`. 
This does not work.

2022-11-24 15:10 UTC, Martchus commented
No. I suggested to update the spec file for building the openQA-single-instance package so that this package has a dependency to the openQA package with a fixed version (similar like it is already done for other openQA-* packages). The spec file is contained by this repo so you'll just have to amend your commit.

2022-11-29 13:09 UTC, a-kpappas commented
I am not familiar enough with spec files  to make a change in that big of a file. I will close this and keep my fork. Hopefully it won't be necessary by the time Leap 15.5 is released next year.

2022-11-29 13:09 UTC, closed without merging