OpenQA::Schema::ResultSet::DeveloperSessions: Extract method
os-autoinst/openQA pull request #4915
Opened 2022-11-24 14:54 UTC by okurz

2022-11-24 15:12 UTC, Martchus requested changes

2022-11-24 15:12 UTC, Martchus commented on lib/OpenQA/Schema/ResultSet/DeveloperSessions.pm
> +    my ($res, $worker_id, $session_exists) = $schema->txn_do(sub { self->find_or_create_session($job_id, $user_id) });
```suggestion
    my ($res, $worker_id, $session_exists) = $schema->txn_do(sub { $self->find_or_create_session($job_id, $user_id) });
```

2022-11-24 19:05 UTC, perlpunk approved these changes

2022-11-25 00:00 UTC, Martchus approved these changes

2022-11-25 00:00 UTC, merged