Condense scheduling debug output to single line
os-autoinst/openQA pull request #4916
Opened 2022-11-24 14:55 UTC by okurz

2022-11-24 15:14 UTC, Martchus requested changes

2022-11-24 15:14 UTC, Martchus commented on lib/OpenQA/Scheduler/Model/Jobs.pm
> +    log_debug("Scheduling: Free workers: ". scalar(@free_workers) . "/$all_workers; Scheduled jobs: " . scalar(keys %$scheduled_jobs));
```suggestion
    log_debug("Scheduling: Free workers: $free_worker_count/$all_workers; Scheduled jobs: " . scalar(keys %$scheduled_jobs));
```

2022-12-06 17:28 UTC, Martchus approved these changes

2022-12-07 14:39 UTC, baierjan approved these changes

2022-12-07 14:40 UTC, merged