JobSettings: only index commonly-queried settings keys
os-autoinst/openQA pull request #4936
Opened 2022-11-29 23:28 UTC by AdamWill

See https://progress.opensuse.org/issues/121054 . When deploying the bigint migration to Fedora, we found it failed, because some entries in this index would now be larger than a hard limit in postgresql:

ERROR:  index row size 2712 exceeds btree version 4 maximum 2704 for index "idx_job_id_value_settings"

These indexes are intended to speed up the `query_for_settings` subquery in lib/OpenQA/Schema/ResultSet/JobSettings.pm - see https://github.com/os-autoinst/openQA/pull/534 . Most queries that go through that subquery will only query for keys in this list. There is one path where arbitrary keys can be queried: the API endpoint that allows for cancelling jobs by setting. I suspect this isn't very heavily used, and when it is used, these are still the most likely settings keys.

This requires a schema version bump and migration, all included.

Related progress issue: https://progress.opensuse.org/issues/121054

Signed-off-by: Adam Williamson <awilliam@redhat.com>

2022-11-29 23:31 UTC, AdamWill commented
An alternative to this would be to change the condition to:

    options => [{where => "key != 'ADVISORY_NVRS'"}],

that's in a way less intrusive, as it would mean almost everything is indexed - on non-Fedora deployments, everything still would be. But it's a weirdly *specific* condition to carry upstream, and would at least need to be clearly commented...

2022-11-29 23:33 UTC, AdamWill commented
Note this still wouldn't make the migration work without manual intervention on Fedora; I'd have to manually drop and recreate the indexes before the bigint conversion. But I don't think we can really fix the migration without lying about the schema versions; we'd have to put the partial index change before the bigint conversion, but the bigint conversion is 97 and this index change would be 98...

2022-12-01 12:04 UTC, Martchus requested changes
I think this conflicts with the newly added route for searching job settings (see `ResultSet/JobSettings.pm`).

From

> hah, man, i bet i can guess what's causing this, too - that damn kde update with a zillion packages in it...
> one of our job settings is a list of the packages in the update

I gather that basically a job setting value that is too long causes the problem. Maybe it makes sense to put that kind of constraint in the `where` clause of `options`. I'm not sure what's possible to put there but it looks like arbitrary SQL. So e.g. `{where => "length(value) < 100"}` might work. (Not sure about the 100. Maybe it makes sense to test at which point the index explodes.)

2022-12-01 14:38 UTC, kraih commented on dbicdh/PostgreSQL/upgrade/97-98/001-auto.sql
> +DROP INDEX idx_job_id_value_settings;
These two indexes do see a lot of use on our production instances, we should be very sure before limiting their scope:
```
 relid | indexrelid | schemaname |   relname    |       indexrelname        | idx_scan | idx_tup_read | idx_tup_fetch
-------+------------+------------+--------------+---------------------------+----------+--------------+---------------
 16513 |      17780 | public     | job_settings | idx_value_settings        |    38833 |      6342596 |         57192
 16513 |    2342927 | public     | job_settings | idx_job_id_value_settings | 42807954 |   1528570202 |    1036367663
```

2022-12-01 14:45 UTC, kraih commented
> I think this conflicts with the newly added route for searching job settings (see `ResultSet/JobSettings.pm`).

Don't think so. The new route uses two `LIKE` conditions on the `key` and `value` fields, which cannot benefit from these simple indexes. The query plan should always look something like this:
```
explain analyze SELECT job_id, value FROM job_settings WHERE key LIKE '%_TEST_ISSUES' AND value LIKE '%1234%' AND job_id > 10045222 ORDER BY job_id DESC;
                                                                          QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=638172.66..638172.67 rows=2 width=58) (actual time=5289.447..5334.714 rows=0 loops=1)
   Sort Key: job_id DESC
   Sort Method: quicksort  Memory: 25kB
   ->  Gather  (cost=12729.81..638172.65 rows=2 width=58) (actual time=5289.374..5334.639 rows=0 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Parallel Bitmap Heap Scan on job_settings  (cost=11729.81..637172.45 rows=1 width=58) (actual time=5178.240..5178.242 rows=0 loops=3)
               Recheck Cond: (job_id > 10045222)
               Filter: ((key ~~ '%_TEST_ISSUES'::text) AND (value ~~ '%1234%'::text))
               Rows Removed by Filter: 353214
               Heap Blocks: exact=13075
               ->  Bitmap Index Scan on job_settings_idx_job_id  (cost=0.00..11729.81 rows=946316 width=0) (actual time=103.223..103.224 rows=1069745 loops=1)
                     Index Cond: (job_id > 10045222)
 Planning Time: 0.472 ms
 JIT:
   Functions: 18
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 3.843 ms, Inlining 454.932 ms, Optimization 197.809 ms, Emission 112.099 ms, Total 768.682 ms
 Execution Time: 5424.645 ms
```
Which is terrible, and why i still hope we can add a trigram gin index on the table at some point.

2022-12-01 17:56 UTC, AdamWill commented on lib/OpenQA/Schema/Result/JobSettings.pm
> +          [{where => "key IN ('DISTRI', 'VERSION', 'FLAVOR', 'ARCH', 'BUILD', 'ISO', 'HDD_1', 'WORKER_CLASS')"}],
oh, yes, that's right. I'll change that.

2022-12-01 18:12 UTC, AdamWill commented
> I gather that basically a job setting value that is too long causes the problem. Maybe it makes sense to put that kind of constraint in the `where` clause of `options`. I'm not sure what's possible to put there but it looks like arbitrary SQL. So e.g. `{where => "length(value) < 100"}` might work. (Not sure about the 100. Maybe it makes sense to test at which point the index explodes.)

Well - I think it would "work" in the sense of it would indeed create an index where long values weren't indexed. But what I'd be concerned about is, would that index be used for queries that don't include the same constraint? I am not an expert on any of this stuff, but from reading the docs, my sense is that the postgres query planner figures out, somehow, whether the index can be applied to the query or not. The [examples given in the docs](https://www.postgresql.org/docs/current/indexes-partial.html) are all cases where the query and the index use obviously 'compatible' conditions - it has one example where the index condition is `WHERE NOT (client_ip > inet '192.168.100.0' AND client_ip < inet '192.168.100.255')` and a sample query's condition is `WHERE url = '/index.html' AND client_ip = inet '212.78.10.32'`, for instance. You can see 'obviously' how that works. Another example, the index condition is `WHERE billed is not true` and a query uses the condition `WHERE billed is not true AND order_nr < 10000`. Again, obvious how that works. That section also contains a negative example: a query using the condition `WHERE order_nr = 3501` "cannot use this index" because "the order 3501 might be among the billed or unbilled orders".

So, what I'd be worried about if we used that condition is that the queries would not actually use the index, because the query planner wouldn't know whether any value returned in the query was 100 characters or longer in advance.

I suppose we could add the "length(value) < 100" condition to the conditions in `query_for_settings` too - though I'm damned if I can figure out what the DBIx syntax for that would be. Assuming no other queries have wound up using the same indexes, of course.

2022-12-01 18:17 UTC, AdamWill commented
> Those two indexes do see a lot of use on our production instances, we should be very sure before limiting their scope:

Yes, I kinda expected that would be the case. The alternative suggestion - `where => "key != 'ADVISORY_NVRS'"` - is probably the *safest* choice, overall. It just seems like such a weirdly specific thing to carry upstream!

Once the immediate problem is solved, we should probably add some kind of constraint on settings value lengths, and I will figure a way to adjust Fedora's scheduler to not create very long ones (I can probably have it split the package names over multiple keys if there are a lot of them). But even if we do that *now*, the Fedora instance databases already have these entries. So either we have to handle them somehow - which means doing something like this upstream, or Fedora downstream permanently carrying a slightly different db schema, which doesn't seem like a good idea - or I have to manually delete those rows from the db, and I'm not sure what the consequences of that would be.

2022-12-01 18:23 UTC, AdamWill commented
> Don't think so. The new route uses two `LIKE` conditions on the `key` and `value` fields, which cannot benefit from these simple indexes.

Yep. There's also the path in `query_for_settings` when the key is wrapped in colons - that also uses `LIKE` and so cannot use the existing indexes.

2022-12-02 00:16 UTC, AdamWill commented
So, thinking this through, it might be safer to skip this. I'm trying an alternate approach called "telling lies" :P On our stg db server I've updated all the problematic rows in the db and simply dropped the last build from the list, so now the long string ends at "yakuake-22.08.2-1.fc37" not "zanshin-22.08.2-1.fc37". That should be short enough for the index to work OK. The impact seems to only be what I hoped it would be - the recorded settings for the jobs, e.g. [this one](https://openqa.stg.fedoraproject.org/tests/2283227#settings), now have a little white lie in them, but nothing has blown up at least.

I've also tweaked our bits (scheduler, distri code, and message publisher) to handle a chunked replacement for `ADVISORY_NVRS` - now we'll do `ADVISORY_NVRS_1` with up to 20 builds in it, if there's more than 20 there'll also be `ADVISORY_NVRS_2`, if there's more than 40 there'll be `ADVISORY_NVRS_3` and so on. (I started out with a chunk size of 1, then did some math on how many db rows we'd wind up with and thought "maybe 5", then did some more math and thought "screw it, 20"...) This should prevent the problem happening again if we get more huge updates.

I'll also see if I can do something upstream to set a character limit for key + value. That should avoid others running into the problem without needing to change the indexes.

2022-12-02 01:23 UTC, AdamWill commented
On the whole, that seems to be working. I'm gonna close this PR. I'll look at the "limit total size of key+value" thing tomorrow.

2022-12-02 01:23 UTC, closed without merging