Add pagination for GET /api/v1/jobs
os-autoinst/openQA pull request #4964
Opened 2022-12-21 15:05 UTC by asdil12

https://progress.opensuse.org/issues/121102

2022-12-21 16:32 UTC, kraih submitted a review, later dismissed
You forgot pagination tests with the `Link` headers, like [these](https://github.com/os-autoinst/openQA/blob/c73687c22fdee12430e1dab26365347517101840/t/api/11-bugs.t#L91-L139).

2022-12-22 13:25 UTC, asdil12 commented
> You forgot pagination tests with the `Link` headers, like [these](https://github.com/os-autoinst/openQA/blob/c73687c22fdee12430e1dab26365347517101840/t/api/11-bugs.t#L91-L139).

I added tests.
Please have a look at how I don't do the pagination properly for the `latest=1` case which would be hard due to the deduplication breaking the `has_more` check.
Maybe you have an idea how this could be handled.
I'm not sure if pagination in that case is actually needed, though.

2022-12-22 14:16 UTC, kraih commented
> Please have a look at how I don't do the pagination properly for the `latest=1` case which would be hard due to the deduplication breaking the `has_more` check. Maybe you have an idea how this could be handled. I'm not sure if pagination in that case is actually needed, though.

If none of the global limits applied to it before either, then it's probably fine. Or it was an oversight. 🤷

2022-12-23 09:32 UTC, asdil12 commented
well if I understand it correctly, the global limit did apply before as well as the page, but the page could have less than `$limit` entries - in theory even 0, due to the subquery and the deduplication in perl code.

2022-12-24 08:11 UTC, okurz requested changes
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

2023-01-03 12:26 UTC, asdil12 commented
> The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

Not sure what you mean - the commit message has a ticket reference and a descriptive message.
If you want something else, please elaborate.

2023-01-03 14:52 UTC, kalikiana commented on lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
> +    $validation->optional('limit')->num;
This is duplicated

2023-01-03 14:55 UTC, kalikiana commented
> Not sure what you mean - the commit message has a ticket reference and a descriptive message. If you want something else, please elaborate.

The commit message **only** contains a URL. Generally it's good to have at least a sentence about what is being implemented.

If it was me I'd probably write something like this:

```
By handling `row` and `offset` parameters a subset of jobs can be queried. This relies on on the existing `pagination_links_header` feature.

See: https://progress.opensuse.org/issues/121102
```

2023-01-03 18:36 UTC, okurz commented
> Not sure what you mean - the commit message has a ticket reference and a descriptive message. If you want something else, please elaborate.

Well, for example explain the reasoning and what design choices you made. Doesn't have to be anything fancy. Something like "As already done in commit ... adding pagination for /api/v1/jobs to prevent server overloading", etc.

2023-01-04 10:38 UTC, okurz requested changes

2023-01-04 10:38 UTC, okurz commented on t/api/04-jobs.t
> +        }
duplicated

2023-01-04 10:38 UTC, okurz commented on t/api/04-jobs.t
> +        ok $links->{prev}, 'has previous page';
this looks a bit duplicated and too much reliant on specific index position in arrays. That should be cleaned up a bit although functionally looks fine

2023-01-10 11:16 UTC, Martchus reviewed
Generally ok but consider looking into the points mentioned by @okurz .

2023-01-10 11:33 UTC, kraih commented
Ticket has been reassigned to me, guess i'll clean up the PR.

2023-01-10 14:16 UTC, kraih commented on lib/OpenQA/Schema/ResultSet/Jobs.pm
> +    my @jobs = $self->search($until ? {t_created => {'<=' => $until}} : undef, \%attrs);
This was actually dead code.

2023-01-10 14:31 UTC, closed without merging