Ensure consistent openQA version when installing openQA-local-db
os-autoinst/openQA pull request #4997
Opened 2023-02-13 10:35 UTC by baierjan

As a step one, add version to openQA requirements for openQA-local-db as that package is to be picked and installed by the user.

Reference: https://progress.opensuse.org/issues/124316

2023-02-13 12:00 UTC, okurz requested changes
I know it's just a tiny change but I recommend to state in the git subject line which also ends up in changelog documents what this fixes and then in the details how it's done. Like turn around the first and second line in the git subject line and adjust accordingly.

2023-02-13 12:31 UTC, Martchus approved these changes

2023-02-13 14:41 UTC, perlpunk approved these changes

2023-02-13 14:58 UTC, perlpunk commented
It looks like there is flaky coverage in `lib/OpenQA/Worker/Job.pm`:
https://app.codecov.io/gh/os-autoinst/openQA/pull/4997/indirect-changes

```

        return $self->_upload_results(sub { $callback->({result => INCOMPLETE, newbuild => 1}) });
    }
    if ($reason eq WORKER_COMMAND_CANCEL) {
        log_debug("Considering job $job_id as cancelled/restarted by the user");                 # not covered anymore
        return $self->_upload_results(sub { $callback->({result => USER_CANCELLED}) });          # not covered anymore
    }
    if ($reason eq WORKER_SR_DONE) {
        log_debug("Considering job $job_id as regularly done");
```

2023-02-14 13:55 UTC, okurz commented
> It looks like there is flaky coverage in `lib/OpenQA/Worker/Job.pm`: https://app.codecov.io/gh/os-autoinst/openQA/pull/4997/indirect-changes
> 
> ```
> 
>         return $self->_upload_results(sub { $callback->({result => INCOMPLETE, newbuild => 1}) });
>     }
>     if ($reason eq WORKER_COMMAND_CANCEL) {
>         log_debug("Considering job $job_id as cancelled/restarted by the user");                 # not covered anymore
>         return $self->_upload_results(sub { $callback->({result => USER_CANCELLED}) });          # not covered anymore
>     }
>     if ($reason eq WORKER_SR_DONE) {
>         log_debug("Considering job $job_id as regularly done");
> ```

created https://progress.opensuse.org/issues/124484 . Doesn't need to concern us for this PR.

2023-02-14 13:55 UTC, okurz approved these changes

2023-02-14 13:56 UTC, merged