CLI: Support lower-case test argument passing
os-autoinst/openQA pull request #5038
Opened 2023-03-16 07:08 UTC by okurz

isotovideo from os-autoinst already automatically transforms lower-case
test parameter command line arguments into upper-case test arguments.
openQA so far only checked the validity of upper-case parameters in a
regex. Instead we can just support supplied lower-ase test parameter
command line arguments as well by just ensuring all arguments are
upper-cased.

2023-03-16 12:11 UTC, Martchus requested changes
Wouldn't this upper-case any kind of parameter (and not only ones ending up job settings)? Then it would be very wrong.

2023-03-16 17:35 UTC, okurz commented
> Wouldn't this upper-case any kind of parameter (and not only ones ending up job settings)? Then it would be very wrong.

Yes, I agree :) I haven't checked that. Tests should tell but apparently my working copy of openQA is outdated.

@mergifyio rebase

2023-03-16 17:55 UTC, perlpunk commented
> Wouldn't this upper-case any kind of parameter (and not only ones ending up job settings)? Then it would be very wrong.

Yeah, and it would also uppercase the value of the setting, e.g. `distri=Tumbleweed` => `DISTRI=TUMBLEWEED`

2023-03-17 09:07 UTC, okurz commented
just rebased, not more

2026-03-13 21:38 UTC, okurz commented
> Wouldn't this upper-case any kind of parameter (and not only ones ending up job settings)? Then it would be very wrong.

Fixed this by excluding special parameters

> Yeah, and it would also uppercase the value of the setting, e.g. `distri=Tumbleweed` => `DISTRI=TUMBLEWEED`

Fixed by only upcasing the key

2026-03-16 14:16 UTC, Martchus submitted a review, later dismissed
I would implement this in the controller code where we handle such API requests instead of making the case-insensitive behavior client-specific. This would avoid the problems mentioned in inline comments.

2026-03-16 14:16 UTC, Martchus commented on lib/OpenQA/Command.pm
> +my $RESERVED_API_KEYS_RE = qr/^(async|scheduled_product_clone_id)$/;
Is this really an exhaustive list? How will we keep this in-sync with reality? Note that tests are unlikely to fail because you've implemented the upper-casing within `openqa-cli` which we don't involve in tests of API routes.

2026-03-16 14:16 UTC, Martchus commented on lib/OpenQA/Command.pm
> +sub parse_params ($self, $args, $param_file, $uc_keys = 0) {
For what routes is still called? Note that there are many routes that require lower-case parameters, e.g. `distri` (and not `DISTRI`). So this look still very wrong.

Note that there's also a way of specifying parameters via a JSON file. This alternative approach doesn't seem to be altered which means both are now inconsistent.

2026-03-16 14:16 UTC, Martchus commented on t/43-cli-schedule.t
> +    is $res, 0, 'zero return-code if all jobs are ok with lower-case arguments';
This definitely also needs the opposite test: Routes that expect lower-case keys still work.

2026-04-10 15:00 UTC, okurz commented on lib/OpenQA/Command.pm
> +my $RESERVED_API_KEYS_RE = qr/^(async|scheduled_product_clone_id)$/;
I now moved the functionality into lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm `create` where we already called `uc`. There we know that this list actually *is* exhaustive as no other parameters had been extracted before calling `uc`.

2026-04-10 15:01 UTC, okurz commented on lib/OpenQA/Command.pm
> +sub parse_params ($self, $args, $param_file, $uc_keys = 0) {
I now moved the functionality into lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm `create` where we already called `uc` which should means that we handle the transformation more low level so should ensure consistent behaviour.

2026-04-10 15:01 UTC, okurz commented on t/43-cli-schedule.t
> +    is $res, 0, 'zero return-code if all jobs are ok with lower-case arguments';
done

2026-04-10 15:16 UTC, okurz commented
incorporated review suggestions from @Martchus

2026-04-14 10:07 UTC, Martchus commented on t/43-cli-schedule.t
> +
Considering you're now not touching `Command.pm` anymore (except for adding a blank line), this test is probably not needed anymore. Of course it can't hurt so you can also keep it.

2026-04-14 10:07 UTC, Martchus commented on lib/OpenQA/Command.pm
> +
```suggestion
```

2026-04-14 10:51 UTC, okurz commented on lib/OpenQA/Command.pm
> +
done

2026-04-14 10:52 UTC, okurz commented on t/43-cli-schedule.t
> +
true. I would prefer to keep it as it nicely showcases how one can use the CLI

2026-04-14 10:53 UTC, okurz commented
incorporated the suggestion from @Martchus and rebased

2026-04-14 13:55 UTC, Martchus approved these changes

2026-04-15 10:44 UTC, d3flex approved these changes

2026-04-15 10:45 UTC, merged