Update dashboard.scss
os-autoinst/openQA pull request #5077
Opened 2023-04-15 13:45 UTC by Lokeshsri11

As we saw that the progress bar skipped the white color and the results written on it were also in white text, so if we change it to black text it will be easier to see.

2023-04-15 17:38 UTC, Martchus requested changes
The commit message needs to be way more specific, e.g. `Improve contrast of progress bar text`.

This is nothing you need to change: The word "palette" is written with just one "l" (unlike on your screenshot).

2023-04-15 17:38 UTC, Martchus commented on assets/stylesheets/dashboard.scss
> +    }
No strong opinion but I'd use either color names or the `rgb` syntax consistently and I'd also avoid the nested blocks:

```suggestion
    .progress-bar-failed a { color: white; }
    .progress-bar-skipped a { color: black; }
```

2023-04-17 01:44 UTC, Lokeshsri11 commented
@Martchus Is everything alright now ?

2023-04-17 08:34 UTC, Martchus commented on assets/stylesheets/dashboard.scss
> +        a { color: Black; }
```suggestion
        a { color: black; }
```

2023-04-17 12:24 UTC, Lokeshsri11 commented
> The commit message still needs improvement, not only the PR title.

done

2023-04-17 12:55 UTC, Martchus commented
No, you haven't. You've only changed the PR title. And you have created 3 separate commits. It would have been nicer in this case to simply amend the first commit. I can manually squash the commits for you if you like (and also reword them by the way). However, as a learning exercise I recommend to fix this via an interactive rebase locally (and then force-pushing the result).

2023-04-17 13:01 UTC, Lokeshsri11 commented
> No, you haven't. You've only changed the PR title. And you have created 3 separate commits. It would have been nicer in this case to simply amend the first commit. I can manually squash the commits for you if you like (and also reword them by the way). However, as a learning exercise I recommend to fix this via an interactive rebase locally (and then force-pushing the result).

You're right, I apologize for the oversight. It would have been better to amend the first commit instead of creating separate commits for each change. Thank you for bringing this to my attention. I appreciate the suggestion to fix this via an interactive rebase locally and force-pushing the result. I will make sure to follow this approach in the future to keep the commit history clean and organized. Thank you for the opportunity to learn from this experience And yes, this time you can squash manually if you do not have any problem.

2023-04-25 13:06 UTC, okurz commented
@Lokeshsri11 actually I think this could be a good opportunity for you to fix the git commits. Our expectation is that rewording/updating/squashing commits is trivial unless one uses only the github webUI to create commits. So I suggest you try to patch up commits using a command line and update the PR.

2023-04-26 11:40 UTC, Lokeshsri11 commented
> @Lokeshsri11 actually I think this could be a good opportunity for you to fix the git commits. Our expectation is that rewording/updating/squashing commits is trivial unless one uses only the github webUI to create commits. So I suggest you try to patch up commits using a command line and update the PR.

Ok Oliver, I'll squash this project and rewrite the description

2023-04-27 08:13 UTC, Lokeshsri11 commented
Sir, I am not getting PR no. #5077, all other PR are available in my terminal to edit or squash but this one are not.
![2023-04-27](https://user-images.githubusercontent.com/93934416/234801387-c99e1f65-caba-44fd-b1c0-09049da530d6.png)

2023-04-27 09:57 UTC, okurz commented
ok, you created a new PR so you can close this one now. What I would have preferred if you could update *this* PR with new commits, not create another PR. Maybe this is something you could still try here? :)

2023-04-27 12:29 UTC, Lokeshsri11 commented
> ok, you created a new PR so you can close this one now. What I would have preferred if you could update _this_ PR with new commits, not create another PR. Maybe this is something you could still try here? :)

Yes sir, I tried but what was the problem, when I had raised this PR, then it was not from any branch because at that time I had not set up local, changed it directly to GitHub UI, so when I went to squash it today, it was not happening, because of this I had to make a new PR,  But now all the PR I have made are in all the branches, so squashing etc. is being done comfortably in it.

2023-04-27 12:38 UTC, closed without merging