Fix duplication of Devel::Cover requirements specified
os-autoinst/openQA pull request #5117
Opened 2023-05-04 12:13 UTC by okurz

2023-05-04 14:08 UTC, Martchus requested changes
It doesn't look like you've ran `make update-deps`.

2023-05-04 19:40 UTC, Martchus approved these changes

2023-05-05 08:38 UTC, kalikiana approved these changes

2023-05-05 08:58 UTC, okurz commented
@Mergifyio rebase

2023-05-05 09:45 UTC, merged

2023-05-05 12:16 UTC, perlpunk commented
#5122 fixes the undeclared cover_requires