Handle updated/closed PRs via webhook
os-autoinst/openQA pull request #5133
Opened 2023-05-12 17:01 UTC by Martchus

* Cancel a previously scheduled product when a PR is updated
  or closed.
* Introduce the CANCELLED status of a scheduled product so this
  is visible in the UI. Jobs belonging to CANCELLED scheduled
  products might later be treated differently by the cleanup as
  well.
* Related ticket: https://progress.opensuse.org/issues/127949

2023-05-19 08:39 UTC, okurz requested changes
Could you clarify a bit more about the introduction of the CANCELLED status for scheduled products.
1. What effect does that have on non-webhook related product scheduling?
2. It sounds like a good idea but why did we not need that yet for non-webhook related product scheduling?

2023-05-19 08:39 UTC, okurz commented on t/39-scheduled_products-table.t
> +
I'd prefer to revert those unrelated whitespace changes

2023-05-19 08:58 UTC, Martchus commented
> What effect does that have on non-webhook related product scheduling?

None at all as so far only the webhook route allows the cancellation of a scheduled produce. We *could* allow this in general. Regardless of how the cancellation happens it means that jobs of the specific scheduled product will be cancelled and become immediate subject to cleanup. (The cleanup part hasn't been implemented yet.)

> It sounds like a good idea but why did we not need that yet for non-webhook related product scheduling?

There's a mechanism to obsolete old builds where "old build" means "jobs matching the specified parameters". We should not use that here. We simply want to obsolete the set of jobs from the previous PR version, regardless how parameters might have changed. We also don't want to obsolete production jobs that happen to use the same parameters than CI jobs. We likely also want more aggressive cleanup as PR might be updated very frequently (similar to what OBS does).

2023-05-19 15:17 UTC, Martchus commented
I've been adding comments to explain the different statuses a scheduled product can have.

2023-05-19 16:42 UTC, okurz approved these changes

2023-05-19 18:14 UTC, Martchus commented on lib/OpenQA/Schema/Result/ScheduledProducts.pm
> +sub cancel ($self, $reason = 'PR has changed') {
You've definitely spotted a not so nice workaround here. Unfortunately this default is actually used. Maybe I can try a little bit harder to make it unnecessary.

2023-05-23 13:23 UTC, Martchus commented
The improved descriptions look good on https://github.com/os-autoinst/os-autoinst-distri-example/pull/22 and also the other improvements regarding cancellation and restarting work.

2023-05-23 18:36 UTC, okurz approved these changes

2023-05-24 11:38 UTC, kalikiana approved these changes

2023-05-24 13:13 UTC, merged