Update containers to Leap 15.5
os-autoinst/openQA pull request #5199
Opened 2023-06-12 15:21 UTC by baierjan

To be merged after:
* https://github.com/os-autoinst/openQA/pull/5197
* https://github.com/os-autoinst/openQA/pull/5203

2023-06-14 13:26 UTC, okurz approved these changes

2023-06-14 15:17 UTC, Martchus approved these changes

2023-06-15 08:28 UTC, baierjan commented
To make CI checks happy, we apparently need to update the Circle CI base image first: https://github.com/os-autoinst/openQA/pull/5203

2023-06-16 18:45 UTC, okurz requested changes

2023-06-16 18:45 UTC, okurz commented on .circleci/config.yml
> +    image: registry.opensuse.org/devel/openqa/ci/containers15.5/base:latest
Please don't reintroduce another version string in here. As we rely on what is built in devel:openQA:ci and that repo is for this very CI use anyway we should just whatever is configured there regardless if it's 15.4, 15.5 or Tumbleweed. So just change https://build.opensuse.org/projects/devel:openQA:ci/meta when you are ready for it

2023-06-16 21:08 UTC, okurz reviewed
+1

2023-06-16 21:38 UTC, kalikiana approved these changes

2023-06-16 21:38 UTC, merged