Fix openqa-bootstrap script referencing unbound var
os-autoinst/openQA pull request #5238
Opened 2023-07-10 08:45 UTC by asdil12

https://bugzilla.suse.com/show_bug.cgi?id=1213160
https://progress.opensuse.org/issues/131024

2023-07-10 12:31 UTC, okurz commented on script/openqa-bootstrap
> +[[ -n "$setup_web_proxy" ]] && proxy_args="--proxy=$setup_web_proxy" || proxy_args=""
I would say the usual approach is

```suggestion
proxy_args=""
[[ -n "$setup_web_proxy" ]] && proxy_args="--proxy=$setup_web_proxy"
```

2023-07-10 21:10 UTC, perlpunk approved these changes

2023-07-11 09:43 UTC, merged

2023-07-11 09:44 UTC, okurz requested changes

2023-07-11 09:44 UTC, okurz commented on script/openqa-bootstrap
> +fi
I suggest to solve that as part of the package already. Everything we can do in the package we don't need to do in bootstrap, i.e.:
```suggestion
- pkgs=(openQA-single-instance qemu-arm qemu-ppc qemu-x86 qemu-tools sudo iputils os-autoinst-distri-opensuse-deps)
if [[ $setup_web_proxy == "nginx" ]] ; then
    pkgs=(openQA-single-instance-nginx)
else
    pkgs=(openQA-single-instance)
fi
+ pkgs+=(qemu-arm qemu-ppc qemu-x86 qemu-tools sudo iputils os-autoinst-distri-opensuse-deps)
```