munin: Include context in minion plugin title
os-autoinst/openQA pull request #5350
Opened 2023-10-26 17:32 UTC by kalikiana

We can disambiguate what aspect of the minion setup the failure stems from.

See: https://progress.opensuse.org/issues/138545

2023-10-26 18:54 UTC, perlpunk reviewed
Can you also document that in line 17 and in contrib/munin/config/minion.config?
```
env.webui https://openqa.opensuse.org
```

2023-10-26 18:54 UTC, perlpunk commented on contrib/munin/plugins/minion
> +        title => "Minion Workers - see " . ($ENV{webui} // "https://openqa.opensuse.org") . "/minion/workers"),
```suggestion
        title => "Minion Workers - see " . ($ENV{webui} // "https://openqa.opensuse.org") . "/minion/workers",
```

2023-10-27 14:54 UTC, perlpunk requested changes
Can you add documentation? See https://github.com/os-autoinst/openQA/pull/5350#pullrequestreview-1700425129

2023-10-27 16:59 UTC, perlpunk approved these changes

2023-11-02 11:35 UTC, mimi1vx approved these changes

2023-11-02 11:35 UTC, merged