Add group filter options for /tests
os-autoinst/openQA pull request #5401
Opened 2023-12-19 14:21 UTC by kraih

Based on #5388, and reusing most of the same logic, to bring job group filtering to `/tests` from `/tests/overview`. Similar to the `?match=...` option, this does not have a UI element yet and can only be used by manually entering the query parameter. Since the question of how to extend the filter form with text fields is still open, i consider it out of scope for this PR.

Progress: https://progress.opensuse.org/issues/134933

2023-12-21 17:13 UTC, kalikiana approved these changes
The naming seems... awkward, but it looks pretty good and I honestly don't have a better suggestion so I guess I'm fine with it

2023-12-21 17:59 UTC, kraih commented
Naming is at least consistent with the other PR.

2023-12-22 09:09 UTC, okurz requested changes
Care to add some documentation or help text?

2023-12-22 10:26 UTC, kraih commented
> Care to add some documentation or help text?

Where and in what form? I believe the `?match=...` and `?groupid=...` query parameters are also undocumented for `/tests`.

2023-12-22 10:42 UTC, kraih commented
> > > Care to add some documentation or help text?
> > 
> > 
> > Where and in what form? I believe the `?match=...` and `?groupid=...` query parameters are also undocumented for `/tests`.
> 
> That is correct. How about to mention them all as hover text on the "Search:" label like visible on https://openqa.opensuse.org/tests/ ?

Sure, but not in this PR. I do not want to touch unrelated features here and create a scope creep situation.

2023-12-22 10:53 UTC, kraih commented
I've expanded the tooltip at the bottom of `/tests` for `group_glob` and `not_group_glob`:
<img width="336" alt="popup" src="https://github.com/os-autoinst/openQA/assets/30094/d31a0f85-e37e-45b0-92cb-8f053e9d31c2">

2023-12-22 11:20 UTC, okurz approved these changes
perfect!

2023-12-22 11:20 UTC, merged