Use perlcritc from os-autoinst-commom
os-autoinst/openQA pull request #5459
Opened 2024-02-07 10:18 UTC by b10n1k

2024-02-07 10:19 UTC, okurz requested changes
s/perlcritc/perlcritic/

2024-02-09 08:46 UTC, b10n1k commented
I update the os-autoinst-common as the checkstyle keeps failing https://github.com/os-autoinst/openQA/pull/5465

2024-02-09 08:47 UTC, okurz commented
s/commom/common/

2024-02-09 17:18 UTC, kalikiana approved these changes

2024-02-14 09:48 UTC, kalikiana commented
@b10n1k Please consider this open suggestion, and there is a CI check failing

> s/commom/common/

2025-01-16 15:16 UTC, perlpunk commented
That was done meanwhile

2025-01-16 15:16 UTC, closed without merging