Make developer mode work in single-container setup
os-autoinst/openQA pull request #5471
Opened 2024-02-13 15:35 UTC by Martchus

* Configure the service port delta to zero so the connection to the live view handler is still made via the reverse proxy despite the reverse proxy being exposed on a non-standard port
* Keep docker-compose-based setup as-is because it uses standard ports and also exposes the ports of the individual services
* See https://progress.opensuse.org/issues/153499

2024-02-13 16:21 UTC, kalikiana approved these changes

2024-02-13 21:24 UTC, okurz approved these changes
ok. We should add a test though

2024-02-13 21:26 UTC, okurz requested changes
Actually, sorry, need to rethink. Why should we patch the port in the Dockerfile when the Dockerfile never sets any custom port? Somehow this feels like not the right place. Anyone building a custom container just wrapping openqa-bootstrap would be affected the same, isn't it?

2024-02-14 10:21 UTC, okurz approved these changes
I understand this better now and https://github.com/os-autoinst/openQA/pull/5435 is strongly related and also not that recent bringing in service_port_delta. So this is just the logical consequential change and I agree. We can also consider changing the actual low-level default to use a service_port_delta of 0 but we should make that another explicit pull request even if the change would only affect openQA developers.

2024-02-14 10:22 UTC, merged