Simplify CLI::monitor with 'all' function
os-autoinst/openQA pull request #5485
Opened 2024-02-21 07:40 UTC by okurz

2024-02-21 09:53 UTC, Martchus approved these changes

2024-02-21 09:55 UTC, Martchus requested changes

2024-02-21 09:55 UTC, Martchus commented on lib/OpenQA/CLI/monitor.pm
> +    all { OpenQA::Jobs::Constants::is_ok_result($_) } @$job_results ? 2 : 0;
```suggestion
    all { OpenQA::Jobs::Constants::is_ok_result($_) } @$job_results ? 0 : 2;
```

2024-02-21 09:56 UTC, okurz commented on lib/OpenQA/CLI/monitor.pm
> +    all { OpenQA::Jobs::Constants::is_ok_result($_) } @$job_results ? 2 : 0;
Oops, yes :)

2024-02-26 13:29 UTC, okurz commented on lib/OpenQA/CLI/monitor.pm
> +    all { OpenQA::Jobs::Constants::is_ok_result($_) } @$job_results ? 2 : 0;
Done

2024-02-26 15:17 UTC, Martchus approved these changes

2024-02-29 11:57 UTC, kalikiana approved these changes

2024-02-29 11:57 UTC, merged