WIP -- How would we hide the display on /tests/$id#settings pages? -- Add support for configurable secrets variables
os-autoinst/openQA pull request #5691
Opened 2024-06-11 14:25 UTC by okurz

Related progress issue: https://progress.opensuse.org/issues/162086

2024-06-11 14:34 UTC, Martchus requested changes

2024-06-11 16:23 UTC, okurz commented on lib/OpenQA/Log.pm
> +    $hide_re .= "|$vars->{_HIDE_MATCH_RE}" if $vars->{_HIDE_MATCH_RE};
Both suggestions covered including the fallback to ignore the additional custom stuff and still apply the default. I am still doing a concatenation to form the final regex. With more procedural code we could also use `if /$default_re/ || /$custom_re/` but IMHO it wouldn't be better. WDYT?

2025-02-05 14:58 UTC, Martchus requested changes

2025-02-05 14:58 UTC, Martchus commented on lib/OpenQA/Log.pm
> +    return {map { /($hide_re)/ ? ($_ => '[redacted]') : ($_ => $vars->{$_}) } keys %$vars};
It would probably make sense to compile `$hide_re` into a regex only once outside the `map` call:

```suggestion
    $hide_re = $custom_hide_re ? qr/($hide_re|$custom_hide_re)/ : qr/($hide_re)/;
    return {map { ($_ =~ $hide_re) ? ($_ => '[redacted]') : ($_ => $vars->{$_}) } keys %$vars};
```

2026-04-30 11:10 UTC, okurz commented on lib/OpenQA/Log.pm
> +    $hide_re .= "|$vars->{_HIDE_MATCH_RE}" if $vars->{_HIDE_MATCH_RE};
done

2026-04-30 11:11 UTC, okurz commented
all suggestions incorporated and covered redacting in UI+API

2026-04-30 15:31 UTC, Martchus requested changes

2026-04-30 15:31 UTC, Martchus commented on lib/OpenQA/Schema/Result/Jobs.pm
> +    require OpenQA::Log;
Why can't we just use `OpenQA::Log` normally here?

2026-05-17 09:18 UTC, okurz commented on lib/OpenQA/Schema/Result/Jobs.pm
> +    require OpenQA::Log;
yes, we can. Seems like an old left-over for localized testing. fixed

2026-05-18 08:04 UTC, Martchus approved these changes

2026-05-18 20:46 UTC, perlpunk approved these changes

2026-05-18 20:46 UTC, merged