Use require for loading OpenQA::Test::Database
os-autoinst/openQA pull request #5756
Opened 2024-07-11 11:20 UTC by perlpunk

It does a

    plan skip_all ...

in its main code, which is effectively an exit.
Since that happens in a BEGIN block currently during a 'use', it won't execute any INIT blocks any more in perl version >= 5.38. But the -c compile check is running in an INIT block.

Issue: https://progress.opensuse.org/issues/162866

2024-07-11 11:26 UTC, okurz requested changes
Please rephrase the git commit message subject line to state the "Why", not the "What".

Now seeing the code I remember that already in many other cases we applied the best practice to not use any Test::More calls in test helper libraries so maybe we can do that instead? So replace the "plan skip_all" in OpenQA::Test::Database with a "warn" and empty return maybe? As we check for warnings in tests that would still prevent that tests are not executed unnoticed.

2024-07-11 11:27 UTC, perlpunk commented on t/03-auth.t
> +require OpenQA::Test::Database;
Really?

2024-07-11 11:31 UTC, perlpunk commented
Feel free to take over the ticket

2024-07-11 11:44 UTC, perlpunk commented on t/03-auth.t
> +require OpenQA::Test::Database;
Also that's a bit inaccurate. It's to *avoid* happening `plan skip_all` in BEGIN

2024-07-11 13:00 UTC, Martchus approved these changes

2024-07-11 13:03 UTC, Martchus commented
But yes, the commit message should be something like "Fix compile checks ..." to state the why.

I don't think adding a comment on every require is necessary, though. Maybe we can enforce this via a style check or make our even add tests for this.

2024-07-16 08:42 UTC, okurz approved these changes

2024-07-16 08:42 UTC, merged