Add help on how to exclude groupless jobs from WebUI
os-autoinst/openQA pull request #5830
Opened 2024-08-07 11:50 UTC by r-richardson

Add a small help text on how to filter out groupless jobs using the WebUI

Related Ticket: https://progress.opensuse.org/issues/155398

2024-08-07 11:52 UTC, okurz approved these changes

2024-08-07 11:55 UTC, perlpunk commented on templates/webapi/test/list.html.ep
> +    . '<p>It is possible to filter jobs by comments using the <code>comment</code> query parameter, e.g. <code>comment=boo%23123</code> to search for jobs referencing Bugzilla ticket 123.</p>'
You accidentally removed the comma:
```suggestion
    . '<p>It is possible to filter jobs by comments using the <code>comment</code> query parameter, e.g. <code>comment=boo%23123</code> to search for jobs referencing Bugzilla ticket 123.</p>',
```

2024-08-08 10:31 UTC, perlpunk requested changes
See my comment

2024-08-09 09:55 UTC, kalikiana approved these changes

2024-08-09 10:07 UTC, perlpunk approved these changes

2024-08-09 11:03 UTC, merged