Fix linkify to only link to proper URLs
os-autoinst/openQA pull request #5920
Opened 2024-09-11 11:41 UTC by perlpunk

This doesn't check for really well formed URLs, but it limits the matching to only allowed characters in URIs.
It makes up for escapeForHtml() being already called, so it matches `&amp;` separately.

Tested with:

    # "> should be excluded
    "https://github.com/os-autoinst/openQA.git"
    <https://github.com/os-autoinst/os-autoinst.git>
    # ) should be included
    https://de.wikipedia.org/wiki/Queen_(Band)
    # query strings should be included
    https://github.com/os-autoinst/openQA?foo=1%20&bar=*2

Single quotes actually can be part of URIs so that's something we should adapt
in our code (and use double quotes, or I remember back in usenet times we used
`<http://...>` whenever referring to a URL in plain text).

We could use this as a workaround until an according PR to https://github.com/IonicaBizau/anser has been made.
There is a related issue: https://github.com/IonicaBizau/anser/issues/63

Alternative to
* https://github.com/os-autoinst/os-autoinst/pull/2544

Issue: https://progress.opensuse.org/issues/166676

2024-09-11 11:49 UTC, okurz requested changes

2024-09-11 12:07 UTC, okurz reviewed
+1

2024-09-11 12:10 UTC, okurz commented on assets/javascripts/anser-import.js
> +  const re = /(https?:\/\/([A-Za-z0-9#;/?:@=+$,_.!~*()[\]-]|&amp;)+)/gm;
I would be ok if we change all use of `'` to `"` when quoting URLs

2024-09-11 12:23 UTC, perlpunk commented
https://github.com/IonicaBizau/anser/pull/75

2024-09-11 17:09 UTC, perlpunk commented
I added a test

2024-09-11 19:22 UTC, Martchus approved these changes

2024-09-12 06:07 UTC, b10n1k approved these changes

2024-09-12 08:48 UTC, merged