Improve minion guards for needle tasks
os-autoinst/openQA pull request #5961
Opened 2024-09-30 09:42 UTC by perlpunk

In OpenQA::Task::Needle::Save we are now using a `limit_needle_task` guard plus one for `git_clone_${needledir}_task`.

So in OpenQA::Task::Git::Clone we don't need the global limit_needle_task anymore.

Issue: https://progress.opensuse.org/issues/164898

2024-09-30 10:39 UTC, Martchus requested changes
We probably need the same for the delete needle task.

2024-09-30 10:46 UTC, perlpunk commented
> We probably need the same for the delete needle task.

why?

2024-09-30 13:41 UTC, perlpunk commented
> Because it also invokes Git commands on a needle checkout (so far only using the `limit_needle_task` lock).

Oh, the git operation is hidden in OpenQA::Schema::Result::Needles. I only looked at OpenQA::Task::Needle::Delete and didn't expect it elsewhere :(

2024-10-01 09:12 UTC, okurz commented
@mergifyio rebase

2024-10-02 14:00 UTC, perlpunk commented
I updated all git gru tasks to use a guard per directory instead of the global one

2024-10-02 15:01 UTC, perlpunk commented
There seems to be flaky coverage in `lib/OpenQA/Shared/Controller/Running.pm`. We don't see it because the coverage decrease is so low, but going to the report I can see it in the indirect changes ta often:
```
     # setup a function to stop streaming again
     my $timer_id;
     my $close_connection = sub ($self, @) {     # line 204-206 reported as uncovered
         Mojo::IOLoop->remove($timer_id);
         $self->finish;
     };
 
     # setup a recurring timer to send the last screenshot to the client
```

2024-10-02 16:25 UTC, okurz approved these changes

2024-10-03 06:19 UTC, b10n1k approved these changes

2024-10-03 06:23 UTC, merged