Install docs: Clarify when and how to add repos on SLE
os-autoinst/openQA pull request #5987
Opened 2024-10-08 10:33 UTC by asdil12

Ticket: https://progress.opensuse.org/issues/132458

2024-10-08 11:56 UTC, Martchus approved these changes

2024-10-08 18:36 UTC, okurz requested changes

2024-10-08 18:36 UTC, okurz commented on docs/Installing.asciidoc
> +or the official repositories using SUSEConnect by running the following commands.
I don't think it's a choice to use the development version repository *or* official repositories. A lot of dependencies are only in the SLE module and PackageHub so I don't think those are alternative. How did you come to that conclusion? Did you try it out?

2024-10-10 12:13 UTC, Martchus commented on docs/Installing.asciidoc
> +On SLE some repositories have to be added.
I'd phrase it more distinctly from adding repositories (which probably needs to be done in *addition*):
```suggestion
On SLE certain modules have to be enabled.
```

2024-10-10 14:58 UTC, okurz approved these changes

2024-10-10 15:15 UTC, merged