Add config option to restrict asset downloads to logged-in users
os-autoinst/openQA pull request #6082
Opened 2024-12-12 11:31 UTC by Martchus

* Disallow unauthenticated access to assets in web application routes
* Does NOT cover access served via Apache/NGINX
* Does NOT cover adjusting the cache service and additional tooling like the `openqa-clone-job` script
* See https://progress.opensuse.org/issues/170380

2024-12-12 14:59 UTC, okurz requested changes
Looks pretty clean. Can openQA jobs on workers still access assets during job runs, e.g. to read a iso or qcow file needed for test execution?

2024-12-12 14:59 UTC, okurz commented on etc/openqa/openqa.ini
> +## whether authentication is required to access assets; does NOT affect assets made available directly via e.g. Apache or NGINX
```suggestion
## whether authentication is required to access assets; does NOT affect assets made available directly via a web proxy, e.g. Apache/NGINX
```

2024-12-12 15:09 UTC, Martchus commented
> Can openQA jobs on workers still access assets during job runs, e.g. to read a iso or qcow file needed for test execution?

No, they cannot (except via NFS which is probably completely out of scope). The cache service is one of many open points I added on https://progress.opensuse.org/issues/174154. With https://github.com/Martchus/openQA/commit/32e1b30434f09ff71d242d5f8f51b68e0090d05a (which is referenced in the progress issue) this would likely work.

2024-12-12 15:52 UTC, okurz commented
> > Can openQA jobs on workers still access assets during job runs, e.g. to read a iso or qcow file needed for test execution?
> 
> No, they cannot (except via NFS which is probably completely out of scope). The cache service is one of many open points I added on https://progress.opensuse.org/issues/174154. With [Martchus@32e1b30](https://github.com/Martchus/openQA/commit/32e1b30434f09ff71d242d5f8f51b68e0090d05a) (which is referenced in the progress issue) this would likely work.

Well, worker instances having direct access to the openQA base dir still work which includes cases like worker instances running on the same host as the webUI – which can even be considered the default for tiny instances – as well as when having access over NFS. How about you state that in the explanatory comment in openqa.ini. Then I guess we can merge this limited-scope feature

2024-12-13 16:27 UTC, perlpunk approved these changes

2024-12-13 16:28 UTC, merged